"""
Code Generator Engine for C configuration parsing and serialization.
Pure Python 3 standard library.
"""

import sys
sys.dont_write_bytecode = True

from typing import List, Dict, Optional, Any, Union
from .schema_model import (
    FieldType, PrimitiveType, StringType, EnumType, ArrayType, NamedMapType,
    StructType, TaggedUnionType, VariantRule, Field,
    TYPE_BOOL, TYPE_INT, TYPE_INT64, TYPE_UINT32, TYPE_SIZE_T, TYPE_DOUBLE
)
from .c_writer import CWriter

class CodegenEngine:
    def __init__(self, schemas: List[Union[EnumType, StructType, TaggedUnionType]]):
        self.schemas = schemas

    def _get_guard(self, obj: Any) -> Optional[str]:
        return getattr(obj, "guard", None)

    def _get_var_guard(self, var: tuple) -> Optional[str]:
        if len(var) > 3 and isinstance(var[3], str):
            return var[3]
        if len(var) > 2 and isinstance(var[2], str):
            return var[2]
        return None

    def _field_value_decl_str(self, f: Field, name: str) -> str:
        if isinstance(f.type, PrimitiveType):
            return f"{f.type.c_type} {name};"
        elif isinstance(f.type, StringType):
            return f"char {name}[{f.type.max_length}];"
        elif isinstance(f.type, EnumType):
            return f"{f.type.c_type} {name};"
        elif isinstance(f.type, NamedMapType):
            return f"{f.type.item_c_type} *{name};\n  size_t {name}_count;"
        elif isinstance(f.type, ArrayType):
            if isinstance(f.type.item_type, PrimitiveType):
                item_c = f.type.item_type.c_type
            elif isinstance(f.type.item_type, StringType):
                item_c = "char *"
            elif isinstance(f.type.item_type, StructType):
                item_c = f"{f.type.item_type.c_type}"
            elif isinstance(f.type.item_type, EnumType):
                item_c = f"{f.type.item_type.c_type}"
            else:
                item_c = "void *"
            return f"{item_c} *{name};\n  size_t {name}_count;"
        elif isinstance(f.type, StructType):
            return f"{f.type.c_type} {name};"
        elif isinstance(f.type, TaggedUnionType):
            return f"{f.type.c_type} {name};"
        else:
            return f"/* Unknown type for field {name} */"

    def generate_header(self) -> str:
        w = CWriter()
        w.line("/**")
        w.line(" * @file config_gen.h")
        w.line(" * @brief Auto-generated configuration schemas, structures, serializers, and parsers.")
        w.line(" *")
        w.line(" * ============================================================================")
        w.line(" * WARNING: DO NOT EDIT THIS FILE DIRECTLY!")
        w.line(" * This file is automatically generated by tools/codegen (tools/gen_config.py).")
        w.line(" * Any manual changes will be overwritten on the next code generation run.")
        w.line(" * ============================================================================")
        w.line(" */")
        w.line()
        w.line("/* clang-format off */")
        w.line()
        w.line("#ifndef CONFIG_GEN_H")
        w.line("#define CONFIG_GEN_H")
        w.line()
        w.line("#include <assert.h>")
        w.line("#include <stdbool.h>")
        w.line("#include <stddef.h>")
        w.line("#include <stdint.h>")
        w.line()
        w.line("#include \"audio/processing_parameters.h\"")
        w.line("#include \"audio/sample_format.h\"")
        w.line("#include \"backend/audio_backend.h\"")
        w.line("#include \"config/config_error.h\"")
        w.line("#include \"dsd/sigma_delta_modulator.h\"")
        w.line("#include \"engine/engine_state_types.h\"")
        w.line("#include \"filters/biquad.h\"")
        w.line("#include \"utils/cdsp_macros.h\"")
        w.line()
        w.line("typedef struct cJSON cJSON;")
        w.line()

        # 1. Enums
        for s in self.schemas:
            if isinstance(s, EnumType):
                if s.guard:
                    w.line(f"#if defined({s.guard})")
                if not s.is_external:
                    w.line(f"/** Enum: {s.name} */")
                    w.block_start(f"typedef enum")
                    if s.invalid_val and ("INVALID" in s.invalid_val or "NONE" in s.invalid_val) and "(" not in s.invalid_val:
                        w.line(f"{s.invalid_val} = -1,")
                    for i, var in enumerate(s.variants):
                        v_name = var[0]
                        vg = self._get_var_guard(var)
                        comma = "," if i < len(s.variants) - 1 else ""
                        if vg:
                            w.line(f"#if defined({vg})")
                        w.line(f"{v_name}{comma}")
                        if vg:
                            w.line(f"#endif /* {vg} */")
                    w.block_end(f" {s.c_type};")
                    w.line()
                w.line(f"const char *{s.name}_to_string({s.c_type} val);")
                w.line(f"{s.c_type} {s.name}_from_string(const char *str);")
                if s.guard:
                    w.line(f"#endif /* {s.guard} */")
                w.line()

        # 2. Structs & Tagged Unions forward declarations
        seen_named_maps = set()
        for s in self.schemas:
            if isinstance(s, StructType):
                for f in s.fields:
                    if isinstance(f.type, NamedMapType) and f.type.name not in seen_named_maps:
                        seen_named_maps.add(f.type.name)
                        w.line(f"typedef struct {f.type.item_c_type} {f.type.item_c_type};")
                if not s.is_external:
                    if s.guard:
                        w.line(f"#if defined({s.guard})")
                    w.line(f"typedef struct {s.c_type} {s.c_type};")
                    if s.guard:
                        w.line(f"#endif /* {s.guard} */")
            elif isinstance(s, TaggedUnionType):
                if not s.is_external:
                    if s.guard:
                        w.line(f"#if defined({s.guard})")
                    w.line(f"typedef struct {s.c_type} {s.c_type};")
                    if s.guard:
                        w.line(f"#endif /* {s.guard} */")
        w.line()

        # 3. Full Struct Definitions
        for s in self.schemas:
            if isinstance(s, StructType):
                if not s.is_external:
                    if s.guard:
                        w.line(f"#if defined({s.guard})")
                    w.line(f"/** Struct: {s.name} */")
                    w.block_start(f"struct {s.c_type}")
                    for f in s.fields:
                        fg = self._get_guard(f)
                        if fg:
                            w.line(f"#if defined({fg})")
                        if f.has_flag:
                            if f.aliases and not isinstance(f.type, ArrayType):
                                w.block_start("union")
                                w.line(f"bool has_{f.name};")
                                for a in f.aliases:
                                    w.line(f"bool has_{a};")
                                w.block_end(";")
                            else:
                                w.line(f"bool has_{f.name};")
                        if f.aliases and not isinstance(f.type, ArrayType):
                            w.block_start("union")
                            w.line(self._field_value_decl_str(f, f.name))
                            for a in f.aliases:
                                w.line(self._field_value_decl_str(f, a))
                            w.block_end(";")
                        else:
                            w.line(self._field_value_decl_str(f, f.name))
                        if fg:
                            w.line(f"#endif /* {fg} */")
                    w.block_end(";")
                    if s.guard:
                        w.line(f"#endif /* {s.guard} */")
                    w.line()
            elif isinstance(s, TaggedUnionType):
                if not s.is_external:
                    if s.guard:
                        w.line(f"#if defined({s.guard})")
                    w.line(f"/** Tagged Union: {s.name} */")
                    w.block_start(f"struct {s.c_type}")
                    w.line(f"{s.tag_enum.c_type} {s.tag_field};")
                    if s.extra_fields:
                        for f in s.extra_fields:
                            fg = self._get_guard(f)
                            if fg:
                                w.line(f"#if defined({fg})")
                            if f.has_flag:
                                if f.aliases and not isinstance(f.type, ArrayType):
                                    w.block_start("union")
                                    w.line(f"bool has_{f.name};")
                                    for a in f.aliases:
                                        w.line(f"bool has_{a};")
                                    w.block_end(";")
                                else:
                                    w.line(f"bool has_{f.name};")
                            if f.aliases and not isinstance(f.type, ArrayType):
                                w.block_start("union")
                                w.line(self._field_value_decl_str(f, f.name))
                                for a in f.aliases:
                                    w.line(self._field_value_decl_str(f, a))
                                w.block_end(";")
                            else:
                                w.line(self._field_value_decl_str(f, f.name))
                            if fg:
                                w.line(f"#endif /* {fg} */")
                    w.block_start(f"union")
                    for tag_variant, (field_name, struct_type) in s.variants.items():
                        g = self._get_guard(struct_type)
                        if g:
                            w.line(f"#if defined({g})")
                        w.line(f"{struct_type.c_type} {field_name};")
                        if g:
                            w.line(f"#endif /* {g} */")
                    if s.extra_union_members:
                        for field_name, struct_type in s.extra_union_members:
                            g = self._get_guard(struct_type)
                            if g:
                                w.line(f"#if defined({g})")
                            w.line(f"{struct_type.c_type} {field_name};")
                            if g:
                                w.line(f"#endif /* {g} */")
                    w.block_end(f" {s.union_field};")
                    w.block_end(";")
                    if s.guard:
                        w.line(f"#endif /* {s.guard} */")
                    w.line()

        # 3.5 Named Map Item Struct Definitions
        seen_named_maps = set()
        for s in self.schemas:
            if isinstance(s, StructType):
                for f in s.fields:
                    if isinstance(f.type, NamedMapType) and f.type.name not in seen_named_maps:
                        seen_named_maps.add(f.type.name)
                        mt = f.type
                        w.line(f"/** Named Map Item: {mt.item_c_type} */")
                        w.block_start(f"struct {mt.item_c_type}")
                        w.line("char name[128];")
                        if mt.has_description:
                            w.line("char description[256];")
                        w.line(f"{mt.value_type.c_type} {mt.value_field};")
                        w.block_end(";")
                        w.line()

        # 4. Function Prototypes (init, equal, parse, serialize, free, getters)
        for s in self.schemas:
            if isinstance(s, StructType):
                if s.guard:
                    w.line(f"#if defined({s.guard})")
                w.line(f"void {s.name}_init({s.c_type} *out);")
                w.line(f"bool {s.name}_equal(const {s.c_type} *a, const {s.c_type} *b);")
                w.line(f"int parse_{s.name}(const cJSON *obj, const char *ctx, {s.c_type} *out, config_error_t *err);")
                w.line(f"cJSON *serialize_{s.name}(const {s.c_type} *in);")
                w.line(f"void free_{s.name}_contents({s.c_type} *in);")
                for f in s.fields:
                    if f.has_flag and f.getter_default is not None:
                        if isinstance(f.type, PrimitiveType):
                            w.line(f"{f.type.c_type} {s.name}_get_{f.name}(const {s.c_type} *in);")
                        elif isinstance(f.type, EnumType):
                            w.line(f"{f.type.c_type} {s.name}_get_{f.name}(const {s.c_type} *in);")
                if s.guard:
                    w.line(f"#endif /* {s.guard} */")
                w.line()
            elif isinstance(s, TaggedUnionType):
                if s.guard:
                    w.line(f"#if defined({s.guard})")
                w.line(f"void {s.name}_init({s.c_type} *out);")
                w.line(f"bool {s.name}_equal(const {s.c_type} *a, const {s.c_type} *b);")
                w.line(f"int parse_{s.name}(const cJSON *obj, const char *ctx, {s.c_type} *out, config_error_t *err);")
                w.line(f"cJSON *serialize_{s.name}(const {s.c_type} *in);")
                w.line(f"void free_{s.name}_contents({s.c_type} *in);")
                if s.guard:
                    w.line(f"#endif /* {s.guard} */")
                w.line()

        w.line("#endif /* CONFIG_GEN_H */")
        w.line()
        w.line("/* clang-format on */")
        return w.get_code()

    def generate_source(self) -> str:
        w = CWriter()
        w.line("/**")
        w.line(" * @file config_gen.c")
        w.line(" * @brief Auto-generated configuration parsers, serializers, initializers, and comparators.")
        w.line(" *")
        w.line(" * ============================================================================")
        w.line(" * WARNING: DO NOT EDIT THIS FILE DIRECTLY!")
        w.line(" * This file is automatically generated by tools/codegen (tools/gen_config.py).")
        w.line(" * Any manual changes will be overwritten on the next code generation run.")
        w.line(" * ============================================================================")
        w.line(" */")
        w.line()
        w.line("/* clang-format off */")
        w.line()
        w.line("#include \"config/config_gen.h\"")
        w.line("#include <assert.h>")
        w.line("#include <math.h>")
        w.line("#include <stdio.h>")
        w.line("#include <stdlib.h>")
        w.line("#include <string.h>")
        w.line("#include \"config/cJSON.h\"")
        w.line("#include \"config/config_parser.h\"")
        w.line()

        # Collect all variants per enum c_type
        c_type_variants = {}
        for s in self.schemas:
            if isinstance(s, EnumType):
                if s.c_type not in c_type_variants:
                    c_type_variants[s.c_type] = []
                for var in s.variants:
                    if not any(v[0] == var[0] for v in c_type_variants[s.c_type]):
                        c_type_variants[s.c_type].append(var)

        # 1. Enums implementation
        for s in self.schemas:
            if isinstance(s, EnumType):
                if s.guard:
                    w.line(f"#if defined({s.guard})")
                w.line(f"const char *{s.name}_to_string({s.c_type} val) {{")
                w.indent()
                w.block_start("switch (val)")
                handled = set()
                for var in s.variants:
                    v_name = var[0]
                    json_str = var[1]
                    handled.add(v_name)
                    vg = self._get_var_guard(var)
                    if vg:
                        w.line(f"#if defined({vg})")
                    w.line(f"case {v_name}: return \"{json_str}\";")
                    if vg:
                        w.line(f"#endif")
                for var in c_type_variants.get(s.c_type, []):
                    if var[0] not in handled and var[0] != s.invalid_val:
                        handled.add(var[0])
                        vg = self._get_var_guard(var)
                        if vg:
                            w.line(f"#if defined({vg})")
                        w.line(f"case {var[0]}: return \"Invalid\";")
                        if vg:
                            w.line(f"#endif")
                if s.invalid_val and s.invalid_val not in handled:
                    w.line(f"case {s.invalid_val}: return \"Invalid\";")
                w.block_end()
                w.line("CDSP_UNREACHABLE();")
                w.line("return \"Invalid\";")
                w.dedent()
                w.line("}")
                w.line()

                w.line(f"{s.c_type} {s.name}_from_string(const char *str) {{")
                w.indent()
                invalid_ret = s.invalid_val if s.invalid_val else s.variants[0][0]
                w.line(f"if (!str) return {invalid_ret};")
                for var in s.variants:
                    v_name = var[0]
                    json_str = var[1]
                    aliases = var[2] if len(var) > 2 and isinstance(var[2], list) else []
                    vg = self._get_var_guard(var)
                    if vg:
                        w.line(f"#if defined({vg})")
                    w.line(f"if (strcmp(str, \"{json_str}\") == 0) return {v_name};")
                    for alias in aliases:
                        w.line(f"if (strcmp(str, \"{alias}\") == 0) return {v_name};")
                    if vg:
                        w.line(f"#endif")
                w.line(f"return {invalid_ret};")
                w.dedent()
                w.line("}")
                if s.guard:
                    w.line(f"#endif /* {s.guard} */")
                w.line()

        # 2. Structs implementation
        for s in self.schemas:
            if isinstance(s, StructType):
                if s.guard:
                    w.line(f"#if defined({s.guard})")
                # Init function
                w.line(f"void {s.name}_init({s.c_type} *out) {{")
                w.indent()
                w.line("if (!out) return;")
                w.line(f"memset(out, 0, sizeof({s.c_type}));")
                for f in s.fields:
                    if f.default is not None:
                        if isinstance(f.type, PrimitiveType):
                            val_str = "true" if f.default is True else "false" if f.default is False else str(f.default)
                            w.line(f"out->{f.name} = {val_str};")
                        elif isinstance(f.type, EnumType):
                            w.line(f"out->{f.name} = {f.default};")
                        elif isinstance(f.type, StringType):
                            w.line(f"snprintf(out->{f.name}, sizeof(out->{f.name}), \"%s\", \"{f.default}\");")
                w.dedent()
                w.line("}")
                w.line()

                # Getters for optional fields
                for f in s.fields:
                    if f.has_flag and f.getter_default is not None:
                        ret_type = f.type.c_type
                        val_str = "true" if f.getter_default is True else "false" if f.getter_default is False else str(f.getter_default)
                        w.line(f"{ret_type} {s.name}_get_{f.name}(const {s.c_type} *in) {{")
                        w.indent()
                        w.line(f"if (!in || !in->has_{f.name}) return {val_str};")
                        w.line(f"return in->{f.name};")
                        w.dedent()
                        w.line("}")
                        w.line()

                # Free contents function
                w.line(f"void free_{s.name}_contents({s.c_type} *in) {{")
                w.indent()
                w.line("if (!in) return;")
                for f in s.fields:
                    if isinstance(f.type, ArrayType):
                        if isinstance(f.type.item_type, StringType):
                            w.line(f"if (in->{f.name}) {{")
                            w.indent()
                            w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{ free(in->{f.name}[i]); }}")
                            w.line(f"free(in->{f.name});")
                            w.line(f"in->{f.name} = NULL;")
                            w.line(f"in->{f.name}_count = 0;")
                            w.dedent()
                            w.line("}")
                        elif isinstance(f.type.item_type, StructType):
                            w.line(f"if (in->{f.name}) {{")
                            w.indent()
                            w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{ free_{f.type.item_type.name}_contents(&in->{f.name}[i]); }}")
                            w.line(f"free(in->{f.name});")
                            w.line(f"in->{f.name} = NULL;")
                            w.line(f"in->{f.name}_count = 0;")
                            w.dedent()
                            w.line("}")
                        else:
                            w.line(f"if (in->{f.name}) {{ free(in->{f.name}); in->{f.name} = NULL; in->{f.name}_count = 0; }}")
                    elif isinstance(f.type, NamedMapType):
                        mt = f.type
                        w.line(f"if (in->{f.name}) {{")
                        w.indent()
                        w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{ free_{mt.value_type.name}_contents(&in->{f.name}[i].{mt.value_field}); }}")
                        w.line(f"free(in->{f.name});")
                        w.line(f"in->{f.name} = NULL;")
                        w.line(f"in->{f.name}_count = 0;")
                        w.dedent()
                        w.line("}")
                    elif isinstance(f.type, StructType):
                        w.line(f"free_{f.type.name}_contents(&in->{f.name});")
                w.dedent()
                w.line("}")
                w.line()

                # Parser function
                self._generate_struct_parser(s, w)

                # Serializer function
                self._generate_struct_serializer(s, w)

                # Equal function
                self._generate_struct_equal(s, w)

                if s.guard:
                    w.line(f"#endif /* {s.guard} */")
                w.line()

            elif isinstance(s, TaggedUnionType):
                if s.guard:
                    w.line(f"#if defined({s.guard})")
                # Init function
                w.line(f"void {s.name}_init({s.c_type} *out) {{")
                w.indent()
                w.line("if (!out) return;")
                w.line(f"memset(out, 0, sizeof({s.c_type}));")
                if s.extra_fields:
                    for f in s.extra_fields:
                        if f.default is not None:
                            if isinstance(f.type, PrimitiveType):
                                val_str = "true" if f.default is True else "false" if f.default is False else str(f.default)
                                w.line(f"out->{f.name} = {val_str};")
                            elif isinstance(f.type, EnumType):
                                w.line(f"out->{f.name} = {f.default};")
                w.dedent()
                w.line("}")
                w.line()

                # Free contents function
                w.line(f"void free_{s.name}_contents({s.c_type} *in) {{")
                w.indent()
                w.line("if (!in) return;")
                if s.extra_fields:
                    for f in s.extra_fields:
                        if isinstance(f.type, ArrayType):
                            if isinstance(f.type.item_type, StringType):
                                w.line(f"if (in->{f.name}) {{")
                                w.indent()
                                w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{ free(in->{f.name}[i]); }}")
                                w.line(f"free(in->{f.name});")
                                w.line(f"in->{f.name} = NULL;")
                                w.line(f"in->{f.name}_count = 0;")
                                w.dedent()
                                w.line("}")
                            elif isinstance(f.type.item_type, StructType):
                                w.line(f"if (in->{f.name}) {{")
                                w.indent()
                                w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{ free_{f.type.item_type.name}_contents(&in->{f.name}[i]); }}")
                                w.line(f"free(in->{f.name});")
                                w.line(f"in->{f.name} = NULL;")
                                w.line(f"in->{f.name}_count = 0;")
                                w.dedent()
                                w.line("}")
                            else:
                                w.line(f"if (in->{f.name}) {{ free(in->{f.name}); in->{f.name} = NULL; in->{f.name}_count = 0; }}")
                w.block_start(f"switch (in->{s.tag_field})")
                handled_tags = set()
                for tag_variant, (field_name, struct_type) in s.variants.items():
                    handled_tags.add(tag_variant)
                    g = self._get_guard(struct_type)
                    if g:
                        w.line(f"#if defined({g})")
                    w.line(f"case {tag_variant}: free_{struct_type.name}_contents(&in->{s.union_field}.{field_name}); break;")
                    if g:
                        w.line(f"#endif")
                if s.extra_union_members:
                    for field_name, struct_type in s.extra_union_members:
                        g = self._get_guard(struct_type)
                        if g:
                            w.line(f"#if defined({g})")
                        w.line(f"free_{struct_type.name}_contents(&in->{s.union_field}.{field_name});")
                        if g:
                            w.line(f"#endif")
                for var in s.tag_enum.variants:
                    if var[0] not in handled_tags:
                        vg = self._get_var_guard(var)
                        if vg:
                            w.line(f"#if defined({vg})")
                        w.line(f"case {var[0]}: break;")
                        if vg:
                            w.line(f"#endif")
                if s.tag_enum.invalid_val and s.tag_enum.invalid_val not in handled_tags:
                    w.line(f"case {s.tag_enum.invalid_val}: break;")
                w.block_end()
                w.dedent()
                w.line("}")
                w.line()

                # Tagged Union Parser
                self._generate_tagged_union_parser(s, w)

                # Tagged Union Serializer
                self._generate_tagged_union_serializer(s, w)

                # Tagged Union Equal
                self._generate_tagged_union_equal(s, w)

                if s.guard:
                    w.line(f"#endif /* {s.guard} */")
                w.line()

        w.line("/* clang-format on */")
        return w.get_code()

    def _generate_field_parse_statement(self, f: Field, struct_name: str, target_var: str, json_var: str, ctx_expr: str, w: CWriter):
        flag_ptr = f"&{target_var}->has_{f.name}" if f.has_flag else "NULL"
        if isinstance(f.type, PrimitiveType):
            parse_func = {
                TYPE_BOOL: "parse_json_bool_strict",
                TYPE_INT: "parse_json_int_strict",
                TYPE_SIZE_T: "parse_json_size_t_strict",
                TYPE_DOUBLE: "parse_json_double_strict",
                TYPE_UINT32: "parse_json_uint32_strict",
            }.get(f.type, "parse_json_int_strict")
            w.line(f"if ({parse_func}({json_var}, \"{f.json_key}\", {ctx_expr}, &{target_var}->{f.name}, {flag_ptr}, err) != 0) return -1;")
            for alias in f.aliases:
                w.line(f"if ({parse_func}({json_var}, \"{alias}\", {ctx_expr}, &{target_var}->{f.name}, {flag_ptr}, err) != 0) return -1;")
        elif isinstance(f.type, StringType):
            w.line(f"if (parse_json_str_strict({json_var}, \"{f.json_key}\", {ctx_expr}, {target_var}->{f.name}, sizeof({target_var}->{f.name}), {flag_ptr}, err) != 0) return -1;")
            for alias in f.aliases:
                w.line(f"if (parse_json_str_strict({json_var}, \"{alias}\", {ctx_expr}, {target_var}->{f.name}, sizeof({target_var}->{f.name}), {flag_ptr}, err) != 0) return -1;")
        elif isinstance(f.type, EnumType):
            w.line("{")
            w.indent()
            variants_var = f"{f.name}_{f.type.name}_variants"
            w.line(f"static const config_enum_variant_t {variants_var}[] = {{")
            for var in f.type.variants:
                v_c = var[0]
                v_j = var[1]
                w.line(f"  {{\"{v_j}\", {v_c}}},")
                if len(var) > 2:
                    for alias in var[2]:
                        w.line(f"  {{\"{alias}\", {v_c}}},")
            w.line("  {NULL, 0}")
            w.line("};")
            w.line("int enum_tmp = 0;")
            if f.required:
                w.line(f"if (parse_enum_required({json_var}, \"{f.json_key}\", {variants_var}, {ctx_expr}, &enum_tmp, err) != 0) return -1;")
                w.line(f"{target_var}->{f.name} = ({f.type.c_type})enum_tmp;")
                if f.has_flag:
                    w.line(f"{target_var}->has_{f.name} = true;")
            else:
                w.line("bool has_enum = false;")
                w.line(f"if (parse_enum_optional({json_var}, \"{f.json_key}\", {variants_var}, {ctx_expr}, &enum_tmp, &has_enum, err) != 0) return -1;")
                if f.has_flag:
                    w.line(f"{target_var}->has_{f.name} = has_enum;")
                w.line(f"if (has_enum) {target_var}->{f.name} = ({f.type.c_type})enum_tmp;")
            w.dedent()
            w.line("}")
        elif isinstance(f.type, ArrayType):
            if isinstance(f.type.item_type, PrimitiveType) and f.type.item_type == TYPE_DOUBLE:
                w.line(f"cJSON *arr_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
                w.line(f"if (arr_{f.name}) {{")
                w.indent()
                if f.has_flag:
                    w.line(f"{target_var}->has_{f.name} = true;")
                w.line(f"if (parse_double_array_strict(arr_{f.name}, \"{f.json_key}\", {ctx_expr}, &{target_var}->{f.name}, &{target_var}->{f.name}_count, err) != 0) return -1;")
                w.dedent()
                w.line("}")
            elif isinstance(f.type.item_type, PrimitiveType) and f.type.item_type == TYPE_SIZE_T:
                w.line(f"cJSON *arr_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
                w.line(f"if (arr_{f.name}) {{")
                w.indent()
                if f.has_flag:
                    w.line(f"{target_var}->has_{f.name} = true;")
                w.line(f"if (parse_size_t_array_strict(arr_{f.name}, \"{f.json_key}\", {ctx_expr}, &{target_var}->{f.name}, &{target_var}->{f.name}_count, err) != 0) return -1;")
                w.dedent()
                w.line("}")
            elif isinstance(f.type.item_type, StringType):
                w.line(f"cJSON *arr_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
                if f.aliases:
                    for a in f.aliases:
                        w.line(f"if (!arr_{f.name}) arr_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{a}\");")
                w.line(f"if (arr_{f.name}) {{")
                w.indent()
                if f.allow_null_items:
                    flag_arg = f"&{target_var}->has_{f.name}" if f.has_flag else "NULL"
                    w.line(f"if (parse_labels_array_strict(arr_{f.name}, &{target_var}->{f.name}, &{target_var}->{f.name}_count, {flag_arg}) != 0) {{")
                    w.indent()
                    w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"field '%s' in %s must be an array of strings\", \"{f.json_key}\", {ctx_expr});")
                    w.line("return -1;")
                    w.dedent()
                    w.line("}")
                else:
                    if f.has_flag:
                        w.line(f"{target_var}->has_{f.name} = true;")
                    w.line(f"if (parse_labels_array_strict(arr_{f.name}, &{target_var}->{f.name}, &{target_var}->{f.name}_count, NULL) != 0) {{")
                    w.indent()
                    w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"field '%s' in %s must be an array of strings\", \"{f.json_key}\", {ctx_expr});")
                    w.line("return -1;")
                    w.dedent()
                    w.line("}")
                w.dedent()
                w.line("}")
            elif isinstance(f.type.item_type, StructType):
                w.line(f"cJSON *arr_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
                w.line(f"if (arr_{f.name}) {{")
                w.indent()
                w.line("if (!cJSON_IsArray(arr_" + f.name + ")) {")
                w.indent()
                w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"field '%s' in %s must be an array\", \"{f.json_key}\", {ctx_expr});")
                w.line("return -1;")
                w.dedent()
                w.line("}")
                w.line(f"int count = cJSON_GetArraySize(arr_{f.name});")
                w.line(f"if (count > 0) {{")
                w.indent()
                w.line(f"{target_var}->{f.name} = ({f.type.item_type.c_type} *)calloc(count, sizeof({f.type.item_type.c_type}));")
                w.line(f"if (!{target_var}->{f.name}) {{ config_error_set(err, CONFIG_ERR_PARSE, \"Memory allocation failure\"); return -1; }}")
                w.line(f"{target_var}->{f.name}_count = count;")
                if f.has_flag:
                    w.line(f"{target_var}->has_{f.name} = true;")
                w.line("for (int i = 0; i < count; i++) {")
                w.indent()
                w.line(f"cJSON *item = cJSON_GetArrayItem(arr_{f.name}, i);")
                w.line(f"if (parse_{f.type.item_type.name}(item, \"{f.type.item_type.name} item\", &{target_var}->{f.name}[i], err) != 0) return -1;")
                w.dedent()
                w.line("}")
                w.dedent()
                w.line("}")
                w.dedent()
                w.line("}")
        elif isinstance(f.type, StructType):
            w.line(f"cJSON *obj_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
            w.line(f"if (obj_{f.name}) {{")
            w.indent()
            if f.has_flag:
                w.line(f"{target_var}->has_{f.name} = true;")
            w.line(f"if (parse_{f.type.name}(obj_{f.name}, \"{f.json_key}\", &{target_var}->{f.name}, err) != 0) return -1;")
            w.dedent()
            w.line("}")
        elif isinstance(f.type, TaggedUnionType):
            w.line(f"cJSON *obj_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
            w.line(f"if (obj_{f.name}) {{")
            w.indent()
            if f.has_flag:
                w.line(f"{target_var}->has_{f.name} = true;")
            w.line(f"if (parse_{f.type.name}(obj_{f.name}, \"{f.json_key}\", &{target_var}->{f.name}, err) != 0) return -1;")
            w.dedent()
            w.line("}")
        elif isinstance(f.type, NamedMapType):
            mt = f.type
            w.line(f"cJSON *map_{f.name} = cJSON_GetObjectItemCaseSensitive({json_var}, \"{f.json_key}\");")
            w.line(f"if (map_{f.name} && !cJSON_IsNull(map_{f.name})) {{")
            w.indent()
            w.line(f"if (!cJSON_IsObject(map_{f.name})) {{")
            w.indent()
            w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"%s must be an object\", \"{f.json_key}\");")
            w.line("return -1;")
            w.dedent()
            w.line("}")
            w.line(f"int count = cJSON_GetArraySize(map_{f.name});")
            w.line("if (count > 0) {")
            w.indent()
            w.line(f"{target_var}->{f.name} = ({mt.item_c_type} *)calloc(count, sizeof({mt.item_c_type}));")
            w.line(f"if (!{target_var}->{f.name}) {{ config_error_set(err, CONFIG_ERR_PARSE, \"Memory allocation failure\"); return -1; }}")
            w.line(f"{target_var}->{f.name}_count = count;")
            w.line("int idx = 0;")
            w.line("cJSON *child = NULL;")
            w.line(f"cJSON_ArrayForEach(child, map_{f.name}) {{")
            w.indent()
            w.line(f"{mt.item_c_type} *item = &{target_var}->{f.name}[idx++];")
            w.line("if (child->string) {")
            w.indent()
            w.line("strncpy(item->name, child->string, sizeof(item->name) - 1);")
            w.dedent()
            w.line("}")
            if mt.has_description:
                w.line("parse_json_str_strict(child, \"description\", child->string, item->description, sizeof(item->description), NULL, NULL);")
            w.line(f"if (parse_{mt.value_type.name}(child, child->string ? child->string : \"{mt.name} item\", &item->{mt.value_field}, err) != 0) return -1;")
            w.dedent()
            w.line("}")
            w.dedent()
            w.line("}")
            w.dedent()
            w.line("}")

    def _generate_struct_parser(self, s: StructType, w: CWriter):
        w.line(f"int parse_{s.name}(const cJSON *obj, const char *ctx, {s.c_type} *out, config_error_t *err) {{")
        w.indent()
        w.line("if (!cJSON_IsObject(obj)) {")
        w.indent()
        w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"%s must be an object\", ctx ? ctx : \"{s.name}\");")
        w.line("return -1;")
        w.dedent()
        w.line("}")
        w.line(f"{s.name}_init(out);")
        w.line()

        field_map = {f.name: f for f in s.fields}

        # Branch 1: Struct with variant rules (e.g. resampler, biquad, conv, biquad_combo)
        if s.variant_tag_field and s.variant_rules:
            tag_field_obj = field_map.get(s.variant_tag_field)
            enum_type = tag_field_obj.type
            variants_var = f"{s.name}_{s.variant_tag_field}_variants"
            w.line(f"static const config_enum_variant_t {variants_var}[] = {{")
            for var in enum_type.variants:
                v_c = var[0]
                v_j = var[1]
                vg = self._get_var_guard(var)
                if vg:
                    w.line(f"#if defined({vg})")
                w.line(f"  {{\"{v_j}\", {v_c}}},")
                if len(var) > 2:
                    for alias in var[2]:
                        w.line(f"  {{\"{alias}\", {v_c}}},")
                if vg:
                    w.line("#endif")
            w.line("  {NULL, 0}")
            w.line("};")
            w.line(f"int tag_val = 0;")
            w.line(f"if (parse_enum_required(obj, \"{tag_field_obj.json_key}\", {variants_var}, ctx ? ctx : \"{s.name}\", &tag_val, err) != 0) return -1;")
            w.line(f"out->{s.variant_tag_field} = ({enum_type.c_type})tag_val;")
            w.line()
            w.block_start(f"switch (out->{s.variant_tag_field})")
            handled_tags = set()
            for rule in s.variant_rules:
                for tv in rule.tag_values:
                    w.line(f"case {tv}:")
                    handled_tags.add(tv)
                w.indent()
                w.line("{")
                w.indent()
                if rule.allowed_keys is not None:
                    allowed_keys_list = list(rule.allowed_keys) + s.allowed_extra_keys
                    keys_array_str = ", ".join([f'"{k}"' for k in allowed_keys_list] + ["NULL"])
                    w.line(f"static const char *const allowed[] = {{{keys_array_str}}};")
                    w.line(f"if (validate_unknown_fields(obj, allowed, ctx ? ctx : \"{s.name}\", err) != 0) return -1;")
                if rule.required_keys:
                    req_array_str = ", ".join([f'"{k}"' for k in rule.required_keys] + ["NULL"])
                    w.line(f"static const char *const req[] = {{{req_array_str}}};")
                    w.line(f"if (require_json_fields(obj, req, ctx ? ctx : \"{s.name}\", NULL, err) != 0) return -1;")
                if rule.profile_field and rule.profile_enum:
                    prof_var = f"{rule.profile_enum.name}_variants"
                    w.line(f"const cJSON *prof_item = cJSON_GetObjectItemCaseSensitive(obj, \"{rule.profile_field}\");")
                    w.line("if (prof_item) {")
                    w.indent()
                    w.line(f"static const config_enum_variant_t {prof_var}[] = {{")
                    for var in rule.profile_enum.variants:
                        w.line(f"  {{\"{var[1]}\", {var[0]}}},")
                    w.line("  {NULL, 0}")
                    w.line("};")
                    w.line("int pval = 0;")
                    w.line(f"if (parse_enum_required(obj, \"{rule.profile_field}\", {prof_var}, ctx ? ctx : \"{s.name}\", &pval, err) != 0) return -1;")
                    w.line(f"snprintf(out->{rule.profile_field}, sizeof(out->{rule.profile_field}), \"%s\", {rule.profile_enum.name}_to_string(({rule.profile_enum.c_type})pval));")
                    w.line(f"out->has_{rule.profile_field} = true;")
                    w.dedent()
                    w.line("} else {")
                    w.indent()
                    if rule.profile_fallback_required:
                        fb_array_str = ", ".join([f'"{k}"' for k in rule.profile_fallback_required] + ["NULL"])
                        w.line(f"static const char *const req_fb[] = {{{fb_array_str}}};")
                        w.line(f"if (require_json_fields(obj, req_fb, ctx ? ctx : \"{s.name}\", NULL, err) != 0) return -1;")
                    w.dedent()
                    w.line("}")
                if rule.one_of:
                    for group in rule.one_of:
                        cond_expr = " && ".join([f'!cJSON_GetObjectItemCaseSensitive(obj, "{k}")' for k in group])
                        or_labels = " or ".join([f"'{k}'" for k in group])
                        w.line(f"if ({cond_expr}) {{")
                        w.indent()
                        w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"missing field {or_labels} in %s\", ctx ? ctx : \"{s.name}\");")
                        w.line("return -1;")
                        w.dedent()
                        w.line("}")
                        for idx, k in enumerate(group):
                            check = f"if (cJSON_GetObjectItemCaseSensitive(obj, \"{k}\"))" if idx < len(group) - 1 else "else"
                            w.line(f"{check} {{")
                            w.indent()
                            kf = field_map.get(k)
                            if kf:
                                self._generate_field_parse_statement(kf, s.name, "out", "obj", "ctx ? ctx : \"" + s.name + "\"", w)
                            if k in rule.one_of_sets:
                                target_f, val_c = rule.one_of_sets[k]
                                w.line(f"out->{target_f} = {val_c};")
                            w.dedent()
                            w.line("}")
                if rule.any_of_optional:
                    for idx, (k, (target_f, val_c)) in enumerate(rule.any_of_optional):
                        w.line(f"{'if' if idx == 0 else 'else if'} (cJSON_GetObjectItemCaseSensitive(obj, \"{k}\")) {{")
                        w.indent()
                        kf = field_map.get(k)
                        if kf:
                            self._generate_field_parse_statement(kf, s.name, "out", "obj", "ctx ? ctx : \"" + s.name + "\"", w)
                        w.line(f"out->{target_f} = {val_c};")
                        w.dedent()
                        w.line("}")
                    if rule.default_assignments:
                        w.line("else {")
                        w.indent()
                        for k, v in rule.default_assignments.items():
                            w.line(f"out->{k} = {v};")
                        w.dedent()
                        w.line("}")
                elif rule.default_assignments:
                    for k, v in rule.default_assignments.items():
                        w.line(f"out->{k} = {v};")
                if rule.sets_field:
                    w.line(f"out->{rule.sets_field[0]} = {rule.sets_field[1]};")
                for fn in rule.fields:
                    f = field_map.get(fn)
                    if f:
                        self._generate_field_parse_statement(f, s.name, "out", "obj", "ctx ? ctx : \"" + s.name + "\"", w)
                w.line("break;")
                w.dedent()
                w.line("}")
                w.dedent()
            for var in enum_type.variants:
                if var[0] not in handled_tags:
                    vg = self._get_var_guard(var)
                    if vg:
                        w.line(f"#if defined({vg})")
                    w.line(f"case {var[0]}: break;")
                    if vg:
                        w.line("#endif")
            if enum_type.invalid_val and enum_type.invalid_val not in handled_tags:
                w.line(f"case {enum_type.invalid_val}: break;")
            w.block_end()
            w.line("return 0;")
            w.dedent()
            w.line("}")
            w.line()
            return

        # Branch 2: Struct with nested objects (e.g. mixer with channels: { in, out })
        if s.nested_objects:
            top_level_allowed = [f.json_key for f in s.fields if not f.json_object] + list(s.nested_objects.keys()) + s.allowed_extra_keys
            for f in s.fields:
                if not f.json_object:
                    top_level_allowed.extend(f.aliases)
            keys_array_str = ", ".join([f'"{k}"' for k in top_level_allowed] + ["NULL"])
            w.line(f"static const char *const allowed_keys[] = {{{keys_array_str}}};")
            w.line(f"if (validate_unknown_fields(obj, allowed_keys, ctx ? ctx : \"{s.name}\", err) != 0) return -1;")
            w.line()
            # Required fields check
            req_keys = [f.json_key for f in s.fields if f.required and not f.json_object and not f.aliases]
            if req_keys:
                req_array_str = ", ".join([f'"{k}"' for k in req_keys] + ["NULL"])
                w.line(f"static const char *const req_keys[] = {{{req_array_str}}};")
                w.line(f"if (require_json_fields(obj, req_keys, ctx ? ctx : \"{s.name}\", NULL, err) != 0) return -1;")
                w.line()
            for f in s.fields:
                if f.required and not f.json_object and f.aliases:
                    all_opts = [f.json_key] + f.aliases
                    check_expr = " && ".join([f'!cJSON_GetObjectItemCaseSensitive(obj, "{k}")' for k in all_opts])
                    w.line(f"if ({check_expr}) {{")
                    w.indent()
                    w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"missing field '{f.json_key}' in %s\", ctx ? ctx : \"{s.name}\");")
                    w.line("return -1;")
                    w.dedent()
                    w.line("}")
            # Top level fields
            for f in s.fields:
                if not f.json_object:
                    self._generate_field_parse_statement(f, s.name, "out", "obj", "ctx ? ctx : \"" + s.name + "\"", w)
            # Nested objects
            for nested_name, nested_keys in s.nested_objects.items():
                w.line(f"cJSON *{nested_name}_obj = cJSON_GetObjectItemCaseSensitive(obj, \"{nested_name}\");")
                w.line(f"if (!{nested_name}_obj || !cJSON_IsObject({nested_name}_obj)) {{")
                w.indent()
                w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"missing or invalid required field '{nested_name}' in %s\", ctx ? ctx : \"{s.name}\");")
                w.line("return -1;")
                w.dedent()
                w.line("}")
                nested_allowed_str = ", ".join([f'"{k}"' for k in nested_keys] + ["NULL"])
                w.line(f"static const char *const allowed_{nested_name}_keys[] = {{{nested_allowed_str}}};")
                w.line(f"if (validate_unknown_fields({nested_name}_obj, allowed_{nested_name}_keys, \"{s.name} {nested_name}\", err) != 0) return -1;")
                # Check required nested keys
                nested_req = [f.json_key for f in s.fields if f.json_object == nested_name and f.required]
                if nested_req:
                    nested_req_str = ", ".join([f'"{k}"' for k in nested_req] + ["NULL"])
                    w.line(f"static const char *const req_{nested_name}[] = {{{nested_req_str}}};")
                    w.line(f"if (require_json_fields({nested_name}_obj, req_{nested_name}, \"{s.name} {nested_name}\", NULL, err) != 0) return -1;")
                # Parse fields inside nested object
                for f in s.fields:
                    if f.json_object == nested_name:
                        self._generate_field_parse_statement(f, s.name, "out", f"{nested_name}_obj", f"\"{s.name} {nested_name}\"", w)
            w.line("return 0;")
            w.dedent()
            w.line("}")
            w.line()
            return

        # Branch 3: Standard struct
        allowed_keys = [f.json_key for f in s.fields] + [a for f in s.fields for a in f.aliases] + s.allowed_extra_keys
        keys_array_str = ", ".join([f'"{k}"' for k in allowed_keys] + ["NULL"])
        w.line(f"static const char *const allowed_keys[] = {{{keys_array_str}}};")
        w.line("if (validate_unknown_fields(obj, allowed_keys, ctx ? ctx : \"" + s.name + "\", err) != 0) return -1;")
        w.line()

        # Required fields check
        req_keys = [f.json_key for f in s.fields if f.required and not f.aliases]
        if req_keys:
            req_array_str = ", ".join([f'"{k}"' for k in req_keys] + ["NULL"])
            w.line(f"static const char *const req_keys[] = {{{req_array_str}}};")
            w.line("if (require_json_fields(obj, req_keys, ctx ? ctx : \"" + s.name + "\", NULL, err) != 0) return -1;")
            w.line()
        for f in s.fields:
            if f.required and f.aliases:
                all_opts = [f.json_key] + f.aliases
                check_expr = " && ".join([f'!cJSON_GetObjectItemCaseSensitive(obj, "{k}")' for k in all_opts])
                w.line(f"if ({check_expr}) {{")
                w.indent()
                w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"missing field '{f.json_key}' in %s\", ctx ? ctx : \"{s.name}\");")
                w.line("return -1;")
                w.dedent()
                w.line("}")

        for f in s.fields:
            self._generate_field_parse_statement(f, s.name, "out", "obj", "ctx ? ctx : \"" + s.name + "\"", w)

        w.line("return 0;")
        w.dedent()
        w.line("}")
        w.line()

    def _generate_struct_serializer(self, s: StructType, w: CWriter):
        w.line(f"cJSON *serialize_{s.name}(const {s.c_type} *in) {{")
        w.indent()
        w.line("if (!in) return NULL;")
        w.line("cJSON *obj = cJSON_CreateObject();")
        w.line("if (!obj) return NULL;")

        # Top level fields
        for f in s.fields:
            if f.json_object:
                continue
            has_check = f"if (in->has_{f.name})" if f.has_flag else "if (1)"
            if isinstance(f.type, PrimitiveType):
                if f.type == TYPE_BOOL:
                    w.line(f"{has_check} cJSON_AddBoolToObject(obj, \"{f.json_key}\", in->{f.name});")
                elif f.type in (TYPE_INT, TYPE_INT64, TYPE_UINT32, TYPE_SIZE_T, TYPE_DOUBLE):
                    w.line(f"{has_check} cJSON_AddNumberToObject(obj, \"{f.json_key}\", (double)in->{f.name});")
            elif isinstance(f.type, StringType):
                w.line(f"{has_check} if (in->{f.name}[0]) cJSON_AddStringToObject(obj, \"{f.json_key}\", in->{f.name});")
            elif isinstance(f.type, EnumType):
                w.line(f"{has_check} cJSON_AddStringToObject(obj, \"{f.json_key}\", {f.type.name}_to_string(in->{f.name}));")
            elif isinstance(f.type, ArrayType):
                w.line(f"if (in->{f.name} && in->{f.name}_count > 0) {{")
                w.indent()
                w.line(f"cJSON *arr = cJSON_CreateArray();")
                w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{")
                w.indent()
                if isinstance(f.type.item_type, PrimitiveType):
                    w.line(f"cJSON_AddItemToArray(arr, cJSON_CreateNumber((double)in->{f.name}[i]));")
                elif isinstance(f.type.item_type, StringType):
                    if f.allow_null_items:
                        w.line(f"if (in->{f.name}[i]) cJSON_AddItemToArray(arr, cJSON_CreateString(in->{f.name}[i]));")
                        w.line("else cJSON_AddItemToArray(arr, cJSON_CreateNull());")
                    else:
                        w.line(f"cJSON_AddItemToArray(arr, in->{f.name}[i] ? cJSON_CreateString(in->{f.name}[i]) : cJSON_CreateNull());")
                elif isinstance(f.type.item_type, StructType):
                    w.line(f"cJSON_AddItemToArray(arr, serialize_{f.type.item_type.name}(&in->{f.name}[i]));")
                w.dedent()
                w.line("}")
                w.line(f"cJSON_AddItemToObject(obj, \"{f.json_key}\", arr);")
                w.dedent()
                w.line("}")
            elif isinstance(f.type, StructType):
                w.line(f"cJSON_AddItemToObject(obj, \"{f.json_key}\", serialize_{f.type.name}(&in->{f.name}));")
            elif isinstance(f.type, TaggedUnionType):
                w.line(f"cJSON_AddItemToObject(obj, \"{f.json_key}\", serialize_{f.type.name}(&in->{f.name}));")
            elif isinstance(f.type, NamedMapType):
                mt = f.type
                w.line(f"if (in->{f.name} && in->{f.name}_count > 0) {{")
                w.indent()
                w.line("cJSON *map_obj = cJSON_CreateObject();")
                w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{")
                w.indent()
                w.line(f"cJSON *item_obj = serialize_{mt.value_type.name}(&in->{f.name}[i].{mt.value_field});")
                if mt.has_description:
                    w.line(f"if (in->{f.name}[i].description[0]) {{ cJSON_AddStringToObject(item_obj, \"description\", in->{f.name}[i].description); }}")
                w.line(f"cJSON_AddItemToObject(map_obj, in->{f.name}[i].name, item_obj);")
                w.dedent()
                w.line("}")
                w.line(f"cJSON_AddItemToObject(obj, \"{f.json_key}\", map_obj);")
                w.dedent()
                w.line("}")

        # Nested objects serialization
        if s.nested_objects:
            for nested_name, nested_keys in s.nested_objects.items():
                w.line(f"cJSON *{nested_name}_obj = cJSON_CreateObject();")
                for f in s.fields:
                    if f.json_object == nested_name:
                        has_check = f"if (in->has_{f.name})" if f.has_flag else "if (1)"
                        if isinstance(f.type, PrimitiveType):
                            if f.type == TYPE_BOOL:
                                w.line(f"{has_check} cJSON_AddBoolToObject({nested_name}_obj, \"{f.json_key}\", in->{f.name});")
                            elif f.type in (TYPE_INT, TYPE_INT64, TYPE_UINT32, TYPE_SIZE_T, TYPE_DOUBLE):
                                w.line(f"{has_check} cJSON_AddNumberToObject({nested_name}_obj, \"{f.json_key}\", (double)in->{f.name});")
                w.line(f"cJSON_AddItemToObject(obj, \"{nested_name}\", {nested_name}_obj);")

        w.line("return obj;")
        w.dedent()
        w.line("}")
        w.line()

    def _generate_tagged_union_parser(self, s: TaggedUnionType, w: CWriter):
        w.line(f"int parse_{s.name}(const cJSON *obj, const char *ctx, {s.c_type} *out, config_error_t *err) {{")
        w.indent()
        w.line("if (!cJSON_IsObject(obj)) {")
        w.indent()
        w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"%s must be an object\", ctx ? ctx : \"{s.name}\");")
        w.line("return -1;")
        w.dedent()
        w.line("}")
        w.line(f"{s.name}_init(out);")
        w.line()

        # Branch 1: Flattened Tagged Union (e.g. capture_device_config, playback_device_config)
        if s.is_flattened:
            w.line(f"cJSON *item = cJSON_GetObjectItemCaseSensitive(obj, \"{s.tag_field}\");")
            w.line("if (!cJSON_IsString(item) || !item->valuestring) {")
            w.indent()
            w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"missing field '{s.tag_field}' in %s\", ctx ? ctx : \"{s.name}\");")
            w.line("return -1;")
            w.dedent()
            w.line("}")
            w.line("const char *type_str = item->valuestring;")

            # Calculate expected variants string
            expected_variants = []
            for tag_variant, (field_name, struct_type) in s.variants.items():
                for var in s.tag_enum.variants:
                    if var[0] == tag_variant and var[1] not in s.rejected_variants:
                        expected_variants.append(var[1])
            for alias_key in s.variant_type_aliases.keys():
                if alias_key not in expected_variants:
                    expected_variants.append(alias_key)
            expected_str = ", ".join([f"'{v}'" for v in expected_variants])

            if s.rejected_variants:
                cond = " || ".join([f"strcmp(type_str, \"{v}\") == 0" for v in s.rejected_variants])
                w.line(f"if ({cond}) {{")
                w.indent()
                w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"unknown variant '%s', expected one of {expected_str}\", type_str);")
                w.line("return -1;")
                w.dedent()
                w.line("}")

            if s.extra_fields:
                for f in s.extra_fields:
                    self._generate_field_parse_statement(f, s.name, "out", "obj", f"ctx ? ctx : \"{s.name}\"", w)
                    # If default assignment when not parsed
                    if f.default is not None:
                        val_str = "true" if f.default is True else "false" if f.default is False else str(f.default)
                        w.line(f"if (!out->has_{f.name}) {{ out->{f.name} = {val_str}; }}")

            # Match type_str to payload parsers
            for tag_variant, (field_name, struct_type) in s.variants.items():
                var_names = []
                for var in s.tag_enum.variants:
                    if var[0] == tag_variant and var[1] not in s.rejected_variants:
                        var_names.append(var[1])
                        if len(var) > 2:
                            for a in var[2]:
                                if a not in s.rejected_variants and a not in s.variant_type_aliases:
                                    var_names.append(a)
                if not var_names:
                    continue
                g = self._get_guard(struct_type)
                if g:
                    w.line(f"#if defined({g})")
                match_cond = " || ".join([f"strcmp(type_str, \"{v}\") == 0" for v in var_names])
                w.line(f"if ({match_cond}) {{")
                w.indent()
                w.line(f"out->{s.tag_field} = {tag_variant};")
                w.line(f"return parse_{struct_type.name}(obj, \"{var_names[0]} {s.name}\", &out->{s.union_field}.{field_name}, err);")
                w.dedent()
                w.line("}")
                if g:
                    w.line("#endif")

            for alias_key, (tag_val, member_name, assigns) in s.variant_type_aliases.items():
                # find target struct type from extra_union_members or variants
                payload_type_name = None
                st_obj = None
                for mem_name, st in s.extra_union_members:
                    if mem_name == member_name:
                        payload_type_name = st.name
                        st_obj = st
                        break
                if not payload_type_name:
                    for tv, (mem_name, st) in s.variants.items():
                        if mem_name == member_name:
                            payload_type_name = st.name
                            st_obj = st
                            break
                g = self._get_guard(st_obj) if st_obj else None
                if g:
                    w.line(f"#if defined({g})")
                w.line(f"if (strcmp(type_str, \"{alias_key}\") == 0) {{")
                w.indent()
                w.line(f"out->{s.tag_field} = {tag_val};")
                for ak, av in assigns.items():
                    val_str = "true" if av is True else "false" if av is False else str(av)
                    w.line(f"out->{ak} = {val_str};")
                w.line(f"return parse_{payload_type_name}(obj, \"{alias_key} {s.name}\", &out->{s.union_field}.{member_name}, err);")
                w.dedent()
                w.line("}")
                if g:
                    w.line("#endif")

            w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"unknown variant '%s', expected one of {expected_str}\", type_str);")
            w.line("return -1;")
            w.dedent()
            w.line("}")
            w.line()
            return

        # Branch 2: Standard or Container Tagged Union (e.g. processor_config, filter_config)
        variants_var = f"{s.tag_enum.name}_variants"
        w.line(f"static const config_enum_variant_t {variants_var}[] = {{")
        for var in s.tag_enum.variants:
            v_c = var[0]
            v_j = var[1]
            vg = self._get_var_guard(var)
            if vg:
                w.line(f"#if defined({vg})")
            w.line(f"  {{\"{v_j}\", {v_c}}},")
            if len(var) > 2:
                for alias in var[2]:
                    w.line(f"  {{\"{alias}\", {v_c}}},")
            if vg:
                w.line("#endif")
        w.line("  {NULL, 0}")
        w.line("};")

        if s.requires_parameters_object:
            w.line(f"const cJSON *tag_item = cJSON_GetObjectItemCaseSensitive(obj, \"{s.tag_field}\");")
            w.line("if (!tag_item || !cJSON_IsString(tag_item) || !tag_item->valuestring) {")
            w.indent()
            w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"missing or non-string '{s.tag_field}' in %s\", ctx ? ctx : \"{s.name}\");")
            w.line("return -1;")
            w.dedent()
            w.line("}")
            if s.container_allowed_keys:
                keys_array_str = ", ".join([f'"{k}"' for k in s.container_allowed_keys] + ["NULL"])
                w.line(f"static const char *const allowed_container_keys[] = {{{keys_array_str}}};")
                w.line(f"if (validate_unknown_fields(obj, allowed_container_keys, ctx ? ctx : \"{s.name}\", err) != 0) return -1;")
            w.line("int tag_val = 0;")
            w.line(f"if (parse_enum_required(obj, \"{s.tag_field}\", {variants_var}, ctx ? ctx : \"{s.name}\", &tag_val, err) != 0) return -1;")
            w.line(f"out->{s.tag_field} = ({s.tag_enum.c_type})tag_val;")
            w.line()
            missing_msg = s.missing_params_msg if s.missing_params_msg else f"missing 'parameters' in {s.name} '%s'"
            w.line("const cJSON *params_obj = cJSON_GetObjectItemCaseSensitive(obj, \"parameters\");")
            w.line("if (!params_obj || !cJSON_IsObject(params_obj)) {")
            w.indent()
            w.line(f"config_error_set(err, CONFIG_ERR_PARSE, \"{missing_msg}\", ctx ? ctx : \"{s.name}\");")
            w.line("return -1;")
            w.dedent()
            w.line("}")
        else:
            w.line("int tag_val = 0;")
            w.line(f"if (parse_enum_required(obj, \"{s.tag_field}\", {variants_var}, ctx ? ctx : \"{s.name}\", &tag_val, err) != 0) return -1;")
            w.line(f"out->{s.tag_field} = ({s.tag_enum.c_type})tag_val;")
            w.line()
            w.line("const cJSON *params_obj = cJSON_GetObjectItemCaseSensitive(obj, \"parameters\");")
            w.line("if (!params_obj) params_obj = obj;")

        if s.extra_fields:
            for f in s.extra_fields:
                self._generate_field_parse_statement(f, s.name, "out", "obj", f"ctx ? ctx : \"{s.name}\"", w)

        w.line()
        w.block_start(f"switch (out->{s.tag_field})")
        handled_tags = set()
        for tag_variant, (field_name, struct_type) in s.variants.items():
            handled_tags.add(tag_variant)
            g = self._get_guard(struct_type)
            if g:
                w.line(f"#if defined({g})")
            w.line(f"case {tag_variant}:")
            w.indent()
            w.line(f"if (parse_{struct_type.name}(params_obj, ctx ? ctx : \"{struct_type.name}\", &out->{s.union_field}.{field_name}, err) != 0) return -1;")
            w.line("break;")
            w.dedent()
            if g:
                w.line("#endif")
        for var in s.tag_enum.variants:
            if var[0] not in handled_tags:
                vg = self._get_var_guard(var)
                if vg:
                    w.line(f"#if defined({vg})")
                w.line(f"case {var[0]}: break;")
                if vg:
                    w.line("#endif")
        if s.tag_enum.invalid_val and s.tag_enum.invalid_val not in handled_tags:
            w.line(f"case {s.tag_enum.invalid_val}: break;")
        w.block_end()
        w.line("return 0;")
        w.dedent()
        w.line("}")
        w.line()

    def _generate_tagged_union_serializer(self, s: TaggedUnionType, w: CWriter):
        w.line(f"cJSON *serialize_{s.name}(const {s.c_type} *in) {{")
        w.indent()
        w.line("if (!in) return NULL;")

        # Flattened union serializer
        if s.is_flattened:
            w.line("cJSON *obj = NULL;")
            w.block_start(f"switch (in->{s.tag_field})")
            handled_tags = set()
            for tag_variant, (field_name, struct_type) in s.variants.items():
                handled_tags.add(tag_variant)
                g = self._get_guard(struct_type)
                if g:
                    w.line(f"#if defined({g})")
                w.line(f"case {tag_variant}:")
                w.indent()
                # Check if this tag has alias branching (e.g. WavFile / RawFile)
                has_is_wav_alias = any(ak in ("WavFile", "RawFile") for ak in s.variant_type_aliases.keys()) and tag_variant == "AUDIO_BACKEND_TYPE_FILE"
                if has_is_wav_alias and s.extra_union_members:
                    wav_struct = s.extra_union_members[0][1]
                    w.line("if (in->is_wav) {")
                    w.indent()
                    w.line(f"obj = serialize_{wav_struct.name}(&in->{s.union_field}.{s.extra_union_members[0][0]});")
                    w.line("if (obj) cJSON_AddStringToObject(obj, \"type\", \"WavFile\");")
                    w.dedent()
                    w.line("} else {")
                    w.indent()
                    w.line(f"obj = serialize_{struct_type.name}(&in->{s.union_field}.{field_name});")
                    w.line("if (obj) cJSON_AddStringToObject(obj, \"type\", \"RawFile\");")
                    w.dedent()
                    w.line("}")
                else:
                    tag_str = s.tag_enum.variants[0][1]
                    for var in s.tag_enum.variants:
                        if var[0] == tag_variant:
                            tag_str = var[1]
                            break
                    w.line(f"obj = serialize_{struct_type.name}(&in->{s.union_field}.{field_name});")
                    w.line(f"if (obj) cJSON_AddStringToObject(obj, \"type\", \"{tag_str}\");")
                w.line("break;")
                w.dedent()
                if g:
                    w.line("#endif")
            for var in s.tag_enum.variants:
                if var[0] not in handled_tags:
                    vg = self._get_var_guard(var)
                    if vg:
                        w.line(f"#if defined({vg})")
                    w.line(f"case {var[0]}: break;")
                    if vg:
                        w.line("#endif")
            if s.tag_enum.invalid_val and s.tag_enum.invalid_val not in handled_tags:
                w.line(f"case {s.tag_enum.invalid_val}: break;")
            w.block_end()
            w.line("if (!obj) return NULL;")
            if s.extra_fields:
                for f in s.extra_fields:
                    if f.name == "is_wav":
                        continue
                    has_check = f"if (in->has_{f.name})" if f.has_flag else "if (1)"
                    if isinstance(f.type, PrimitiveType):
                        if f.type == TYPE_BOOL:
                            w.line(f"{has_check} cJSON_AddBoolToObject(obj, \"{f.json_key}\", in->{f.name});")
                        elif f.type in (TYPE_INT, TYPE_INT64, TYPE_UINT32, TYPE_SIZE_T, TYPE_DOUBLE):
                            w.line(f"{has_check} cJSON_AddNumberToObject(obj, \"{f.json_key}\", (double)in->{f.name});")
                    elif isinstance(f.type, EnumType):
                        w.line(f"{has_check} cJSON_AddStringToObject(obj, \"{f.json_key}\", {f.type.name}_to_string(in->{f.name}));")
                    elif isinstance(f.type, ArrayType) and isinstance(f.type.item_type, StringType):
                        w.line(f"if (in->has_{f.name} && in->{f.name}) {{")
                        w.indent()
                        w.line("cJSON *arr = cJSON_CreateArray();")
                        w.line(f"for (size_t i = 0; i < in->{f.name}_count; i++) {{")
                        w.indent()
                        w.line(f"if (in->{f.name}[i]) cJSON_AddItemToArray(arr, cJSON_CreateString(in->{f.name}[i]));")
                        w.line("else cJSON_AddItemToArray(arr, cJSON_CreateNull());")
                        w.dedent()
                        w.line("}")
                        w.line(f"cJSON_AddItemToObject(obj, \"{f.json_key}\", arr);")
                        w.dedent()
                        w.line("}")
            w.line("return obj;")
            w.dedent()
            w.line("}")
            w.line()
            return

        # Standard tagged union serializer
        w.line("cJSON *obj = cJSON_CreateObject();")
        w.line("if (!obj) return NULL;")
        w.line(f"cJSON_AddStringToObject(obj, \"{s.tag_field}\", {s.tag_enum.name}_to_string(in->{s.tag_field}));")
        if s.extra_fields:
            for f in s.extra_fields:
                has_check = f"if (in->has_{f.name})" if f.has_flag else "if (1)"
                if isinstance(f.type, PrimitiveType):
                    if f.type == TYPE_BOOL:
                        w.line(f"{has_check} cJSON_AddBoolToObject(obj, \"{f.json_key}\", in->{f.name});")
                    elif f.type in (TYPE_INT, TYPE_INT64, TYPE_UINT32, TYPE_SIZE_T, TYPE_DOUBLE):
                        w.line(f"{has_check} cJSON_AddNumberToObject(obj, \"{f.json_key}\", (double)in->{f.name});")
                elif isinstance(f.type, StringType):
                    w.line(f"{has_check} if (in->{f.name}[0]) cJSON_AddStringToObject(obj, \"{f.json_key}\", in->{f.name});")
                elif isinstance(f.type, EnumType):
                    w.line(f"{has_check} cJSON_AddStringToObject(obj, \"{f.json_key}\", {f.type.name}_to_string(in->{f.name}));")

        w.block_start(f"switch (in->{s.tag_field})")
        handled_tags = set()
        for tag_variant, (field_name, struct_type) in s.variants.items():
            handled_tags.add(tag_variant)
            g = self._get_guard(struct_type)
            if g:
                w.line(f"#if defined({g})")
            w.line(f"case {tag_variant}:")
            w.indent()
            w.line(f"cJSON_AddItemToObject(obj, \"parameters\", serialize_{struct_type.name}(&in->{s.union_field}.{field_name}));")
            w.line("break;")
            w.dedent()
            if g:
                w.line("#endif")
        for var in s.tag_enum.variants:
            if var[0] not in handled_tags:
                vg = self._get_var_guard(var)
                if vg:
                    w.line(f"#if defined({vg})")
                w.line(f"case {var[0]}: break;")
                if vg:
                    w.line("#endif")
        if s.tag_enum.invalid_val and s.tag_enum.invalid_val not in handled_tags:
            w.line(f"case {s.tag_enum.invalid_val}: break;")
        w.block_end()
        w.line("return obj;")
        w.dedent()
        w.line("}")
        w.line()

    def _generate_field_equal(self, f: Field, w: CWriter):
        if f.type in (TYPE_BOOL, TYPE_INT, TYPE_INT64, TYPE_UINT32, TYPE_SIZE_T) or isinstance(f.type, EnumType):
            w.line(f"if (a->{f.name} != b->{f.name}) return false;")
        elif f.type == TYPE_DOUBLE:
            w.line(f"if (a->{f.name} != b->{f.name}) return false;")
        elif isinstance(f.type, StringType):
            w.line(f"if (strncmp(a->{f.name}, b->{f.name}, sizeof(a->{f.name})) != 0) return false;")
        elif isinstance(f.type, StructType):
            w.line(f"if (!{f.type.name}_equal(&a->{f.name}, &b->{f.name})) return false;")
        elif isinstance(f.type, TaggedUnionType):
            w.line(f"if (!{f.type.name}_equal(&a->{f.name}, &b->{f.name})) return false;")
        elif isinstance(f.type, ArrayType):
            w.line(f"if (a->{f.name}_count != b->{f.name}_count) return false;")
            w.line(f"if (a->{f.name}_count > 0) {{")
            w.indent()
            w.line(f"if (!a->{f.name} || !b->{f.name}) return false;")
            w.line(f"for (size_t i = 0; i < a->{f.name}_count; i++) {{")
            w.indent()
            if isinstance(f.type.item_type, (PrimitiveType, EnumType)):
                w.line(f"if (a->{f.name}[i] != b->{f.name}[i]) return false;")
            elif isinstance(f.type.item_type, StringType):
                w.line(f"if ((a->{f.name}[i] == NULL) != (b->{f.name}[i] == NULL)) return false;")
                w.line(f"if (a->{f.name}[i] && strcmp(a->{f.name}[i], b->{f.name}[i]) != 0) return false;")
            elif isinstance(f.type.item_type, StructType):
                w.line(f"if (!{f.type.item_type.name}_equal(&a->{f.name}[i], &b->{f.name}[i])) return false;")
            w.dedent()
            w.line("}")
            w.dedent()
            w.line("}")
        elif isinstance(f.type, NamedMapType):
            mt = f.type
            w.line(f"if (a->{f.name}_count != b->{f.name}_count) return false;")
            w.line(f"if (a->{f.name}_count > 0) {{")
            w.indent()
            w.line(f"if (!a->{f.name} || !b->{f.name}) return false;")
            w.line(f"for (size_t i = 0; i < a->{f.name}_count; i++) {{")
            w.indent()
            w.line(f"if (strncmp(a->{f.name}[i].name, b->{f.name}[i].name, sizeof(a->{f.name}[i].name)) != 0) return false;")
            if mt.has_description:
                w.line(f"if (strncmp(a->{f.name}[i].description, b->{f.name}[i].description, sizeof(a->{f.name}[i].description)) != 0) return false;")
            w.line(f"if (!{mt.value_type.name}_equal(&a->{f.name}[i].{mt.value_field}, &b->{f.name}[i].{mt.value_field})) return false;")
            w.dedent()
            w.line("}")
            w.dedent()
            w.line("}")

    def _generate_struct_equal(self, s: StructType, w: CWriter):
        w.line(f"bool {s.name}_equal(const {s.c_type} *a, const {s.c_type} *b) {{")
        w.indent()
        w.line("if (a == b) return true;")
        w.line("if (!a || !b) return false;")
        for f in s.fields:
            if f.has_flag:
                w.line(f"if (a->has_{f.name} != b->has_{f.name}) return false;")
                w.line(f"if (a->has_{f.name}) {{")
                w.indent()
                self._generate_field_equal(f, w)
                w.dedent()
                w.line("}")
            else:
                self._generate_field_equal(f, w)
        w.line("return true;")
        w.dedent()
        w.line("}")
        w.line()

    def _generate_tagged_union_equal(self, s: TaggedUnionType, w: CWriter):
        w.line(f"bool {s.name}_equal(const {s.c_type} *a, const {s.c_type} *b) {{")
        w.indent()
        w.line("if (a == b) return true;")
        w.line("if (!a || !b) return false;")
        w.line(f"if (a->{s.tag_field} != b->{s.tag_field}) return false;")
        if s.extra_fields:
            for f in s.extra_fields:
                if f.has_flag:
                    w.line(f"if (a->has_{f.name} != b->has_{f.name}) return false;")
                    w.line(f"if (a->has_{f.name}) {{")
                    w.indent()
                    self._generate_field_equal(f, w)
                    w.dedent()
                    w.line("}")
                else:
                    self._generate_field_equal(f, w)
        w.block_start(f"switch (a->{s.tag_field})")
        handled_tags = set()
        for tag_variant, (field_name, struct_type) in s.variants.items():
            handled_tags.add(tag_variant)
            g = self._get_guard(struct_type)
            if g:
                w.line(f"#if defined({g})")
            w.line(f"case {tag_variant}:")
            w.indent()
            has_is_wav_alias = any(ak in ("WavFile", "RawFile") for ak in s.variant_type_aliases.keys()) and tag_variant == "AUDIO_BACKEND_TYPE_FILE"
            if has_is_wav_alias and s.extra_union_members:
                wav_struct = s.extra_union_members[0][1]
                w.line(f"return a->is_wav ? {wav_struct.name}_equal(&a->{s.union_field}.{s.extra_union_members[0][0]}, &b->{s.union_field}.{s.extra_union_members[0][0]})")
                w.line(f"                 : {struct_type.name}_equal(&a->{s.union_field}.{field_name}, &b->{s.union_field}.{field_name});")
            else:
                w.line(f"return {struct_type.name}_equal(&a->{s.union_field}.{field_name}, &b->{s.union_field}.{field_name});")
            w.dedent()
            if g:
                w.line("#endif")
        for var in s.tag_enum.variants:
            if var[0] not in handled_tags:
                vg = self._get_var_guard(var)
                if vg:
                    w.line(f"#if defined({vg})")
                w.line(f"case {var[0]}: return false;")
                if vg:
                    w.line("#endif")
        if s.tag_enum.invalid_val and s.tag_enum.invalid_val not in handled_tags:
            w.line(f"case {s.tag_enum.invalid_val}: return false;")
        w.block_end()
        w.line("CDSP_UNREACHABLE();")
        w.line("return false;")
        w.dedent()
        w.line("}")
        w.line()
