/**
 * @file config_gen.h
 * @brief Auto-generated configuration schemas, structures, serializers, and parsers.
 *
 * ============================================================================
 * WARNING: DO NOT EDIT THIS FILE DIRECTLY!
 * This file is automatically generated by tools/codegen (tools/gen_config.py).
 * Any manual changes will be overwritten on the next code generation run.
 * ============================================================================
 */

/* clang-format off */

#ifndef CONFIG_GEN_H
#define CONFIG_GEN_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "config/cJSON.h"
#include "config/config_error.h"

struct biquad_filter;
typedef struct biquad_filter biquad_filter_t;

/** Enum: time_unit */
typedef enum {
  TIME_UNIT_INVALID = -1,
  TIME_UNIT_US,
  TIME_UNIT_MS,
  TIME_UNIT_S,
  TIME_UNIT_SAMPLES
} time_unit_t;

const char *time_unit_to_string(time_unit_t val);
time_unit_t time_unit_from_string(const char *str);

/** Enum: delay_unit */
typedef enum {
  DELAY_UNIT_INVALID = -1,
  DELAY_UNIT_MS,
  DELAY_UNIT_US,
  DELAY_UNIT_S,
  DELAY_UNIT_SAMPLES,
  DELAY_UNIT_MM
} delay_unit_t;

const char *delay_unit_to_string(delay_unit_t val);
delay_unit_t delay_unit_from_string(const char *str);

/** Enum: gain_scale */
typedef enum {
  GAIN_SCALE_DB,
  GAIN_SCALE_LINEAR
} gain_scale_t;

const char *gain_scale_to_string(gain_scale_t val);
gain_scale_t gain_scale_from_string(const char *str);

#ifndef FADER_T_DEFINED
#define FADER_T_DEFINED
/** Enum: fader */
typedef enum {
  FADER_NONE = -1,
  FADER_MAIN,
  FADER_AUX1,
  FADER_AUX2,
  FADER_AUX3,
  FADER_AUX4
} fader_t;
#endif /* FADER_T_DEFINED */

const char *fader_to_string(fader_t val);
fader_t fader_from_string(const char *str);

const char *volume_fader_to_string(fader_t val);
fader_t volume_fader_from_string(const char *str);

/** Enum: filter_type */
typedef enum {
  FILTER_TYPE_INVALID = -1,
  FILTER_TYPE_GAIN,
  FILTER_TYPE_VOLUME,
  FILTER_TYPE_LOUDNESS,
  FILTER_TYPE_BIQUAD,
  FILTER_TYPE_CONV,
  FILTER_TYPE_DELAY,
  FILTER_TYPE_BIQUAD_COMBO,
  FILTER_TYPE_DIFF_EQ,
  FILTER_TYPE_DITHER,
  FILTER_TYPE_CLIPPER,
  FILTER_TYPE_LOOKAHEAD_LIMITER
} filter_type_t;

const char *filter_type_to_string(filter_type_t val);
filter_type_t filter_type_from_string(const char *str);

/** Enum: biquad_type */
typedef enum {
  BIQUAD_TYPE_FREE,
  BIQUAD_TYPE_HIGHPASS,
  BIQUAD_TYPE_LOWPASS,
  BIQUAD_TYPE_HIGHPASS_FO,
  BIQUAD_TYPE_LOWPASS_FO,
  BIQUAD_TYPE_HIGHSHELF,
  BIQUAD_TYPE_LOWSHELF,
  BIQUAD_TYPE_HIGHSHELF_FO,
  BIQUAD_TYPE_LOWSHELF_FO,
  BIQUAD_TYPE_PEAKING,
  BIQUAD_TYPE_NOTCH,
  BIQUAD_TYPE_BANDPASS,
  BIQUAD_TYPE_ALLPASS,
  BIQUAD_TYPE_ALLPASS_FO,
  BIQUAD_TYPE_GENERAL_NOTCH,
  BIQUAD_TYPE_LINKWITZ_TRANSFORM
} biquad_type_t;

const char *biquad_type_to_string(biquad_type_t val);
biquad_type_t biquad_type_from_string(const char *str);

/** Enum: steepness_type */
typedef enum {
  STEEPNESS_TYPE_Q,
  STEEPNESS_TYPE_BANDWIDTH,
  STEEPNESS_TYPE_SLOPE
} steepness_type_t;

const char *steepness_type_to_string(steepness_type_t val);
steepness_type_t steepness_type_from_string(const char *str);

/** Enum: conv_type */
typedef enum {
  CONV_TYPE_RAW,
  CONV_TYPE_WAV,
  CONV_TYPE_VALUES,
  CONV_TYPE_DUMMY
} conv_type_t;

const char *conv_type_to_string(conv_type_t val);
conv_type_t conv_type_from_string(const char *str);

/** Enum: biquad_combo_type */
typedef enum {
  BIQUAD_COMBO_TYPE_BUTTERWORTH_HIGHPASS,
  BIQUAD_COMBO_TYPE_BUTTERWORTH_LOWPASS,
  BIQUAD_COMBO_TYPE_LINKWITZ_RILEY_HIGHPASS,
  BIQUAD_COMBO_TYPE_LINKWITZ_RILEY_LOWPASS,
  BIQUAD_COMBO_TYPE_TILT,
  BIQUAD_COMBO_TYPE_N_POINT_PEQ,
  BIQUAD_COMBO_TYPE_GRAPHIC_EQUALIZER
} biquad_combo_type_t;

const char *biquad_combo_type_to_string(biquad_combo_type_t val);
biquad_combo_type_t biquad_combo_type_from_string(const char *str);

/** Enum: dither_type */
typedef enum {
  DITHER_TYPE_NONE,
  DITHER_TYPE_FLAT,
  DITHER_TYPE_HIGHPASS,
  DITHER_TYPE_FWEIGHTED_441,
  DITHER_TYPE_FWEIGHTED_LONG_441,
  DITHER_TYPE_FWEIGHTED_SHORT_441,
  DITHER_TYPE_GESEMANN_441,
  DITHER_TYPE_GESEMANN_48,
  DITHER_TYPE_LIPSHITZ_441,
  DITHER_TYPE_LIPSHITZ_LONG_441,
  DITHER_TYPE_SHIBATA_441,
  DITHER_TYPE_SHIBATA_HIGH_441,
  DITHER_TYPE_SHIBATA_LOW_441,
  DITHER_TYPE_SHIBATA_48,
  DITHER_TYPE_SHIBATA_HIGH_48,
  DITHER_TYPE_SHIBATA_LOW_48,
  DITHER_TYPE_SHIBATA_882,
  DITHER_TYPE_SHIBATA_LOW_882,
  DITHER_TYPE_SHIBATA_96,
  DITHER_TYPE_SHIBATA_LOW_96,
  DITHER_TYPE_SHIBATA_192,
  DITHER_TYPE_SHIBATA_LOW_192
} dither_type_t;

const char *dither_type_to_string(dither_type_t val);
dither_type_t dither_type_from_string(const char *str);

/** Enum: resampler_type */
typedef enum {
  RESAMPLER_TYPE_SYNCHRONOUS,
  RESAMPLER_TYPE_ASYNC_SINC,
  RESAMPLER_TYPE_ASYNC_POLY,
  RESAMPLER_TYPE_SLIP
} resampler_type_t;

const char *resampler_type_to_string(resampler_type_t val);
resampler_type_t resampler_type_from_string(const char *str);

/** Enum: resampler_profile */
typedef enum {
  RESAMPLER_PROFILE_VERY_FAST,
  RESAMPLER_PROFILE_FAST,
  RESAMPLER_PROFILE_BALANCED,
  RESAMPLER_PROFILE_ACCURATE
} resampler_profile_t;

const char *resampler_profile_to_string(resampler_profile_t val);
resampler_profile_t resampler_profile_from_string(const char *str);

/** Enum: fixed_async */
typedef enum {
  FIXED_ASYNC_INPUT,
  FIXED_ASYNC_OUTPUT
} fixed_async_t;

const char *fixed_async_to_string(fixed_async_t val);
fixed_async_t fixed_async_from_string(const char *str);

/** Enum: processor_type */
typedef enum {
  PROCESSOR_TYPE_INVALID = -1,
  PROCESSOR_TYPE_COMPRESSOR,
  PROCESSOR_TYPE_NOISE_GATE,
  PROCESSOR_TYPE_RACE,
  PROCESSOR_TYPE_LOOKAHEAD_LIMITER
} processor_type_t;

const char *processor_type_to_string(processor_type_t val);
processor_type_t processor_type_from_string(const char *str);

/** Enum: pipeline_step_type */
typedef enum {
  PIPELINE_STEP_TYPE_FILTER,
  PIPELINE_STEP_TYPE_MIXER,
  PIPELINE_STEP_TYPE_PROCESSOR
} pipeline_step_type_t;

const char *pipeline_step_type_to_string(pipeline_step_type_t val);
pipeline_step_type_t pipeline_step_type_from_string(const char *str);

/** Enum: audio_backend_type */
typedef enum {
  AUDIO_BACKEND_TYPE_INVALID = -1,
  AUDIO_BACKEND_TYPE_CORE_AUDIO,
  AUDIO_BACKEND_TYPE_ALSA,
  AUDIO_BACKEND_TYPE_PIPEWIRE,
  AUDIO_BACKEND_TYPE_WASAPI,
  AUDIO_BACKEND_TYPE_ASIO,
  AUDIO_BACKEND_TYPE_FILE,
  AUDIO_BACKEND_TYPE_STDIN_OUT,
  AUDIO_BACKEND_TYPE_GENERATOR
} audio_backend_type_t;

const char *audio_backend_type_to_string(audio_backend_type_t val);
audio_backend_type_t audio_backend_type_from_string(const char *str);

/** Enum: signal_type */
typedef enum {
  SIGNAL_TYPE_INVALID = -1,
  SIGNAL_TYPE_SINE,
  SIGNAL_TYPE_SQUARE,
  SIGNAL_TYPE_WHITE_NOISE
} signal_type_t;

const char *signal_type_to_string(signal_type_t val);
signal_type_t signal_type_from_string(const char *str);

/** Enum: sdm_filter */
typedef enum {
  SDM_FILTER_INVALID = -1,
  SDM_FILTER_CLANS4,
  SDM_FILTER_SDM4,
  SDM_FILTER_CLANS5,
  SDM_FILTER_SDM5,
  SDM_FILTER_CLANS6,
  SDM_FILTER_SDM6,
  SDM_FILTER_CLANS7,
  SDM_FILTER_SDM7,
  SDM_FILTER_CLANS8,
  SDM_FILTER_SDM8
} sdm_filter_t;

const char *sdm_filter_to_string(sdm_filter_t val);
sdm_filter_t sdm_filter_from_string(const char *str);

/** Enum: coreaudio_sample_format */
typedef enum {
  COREAUDIO_SAMPLE_FORMAT_INVALID = -1,
  COREAUDIO_SAMPLE_FORMAT_S16,
  COREAUDIO_SAMPLE_FORMAT_S24,
  COREAUDIO_SAMPLE_FORMAT_S32,
  COREAUDIO_SAMPLE_FORMAT_F32
} coreaudio_sample_format_t;

const char *coreaudio_sample_format_to_string(coreaudio_sample_format_t val);
coreaudio_sample_format_t coreaudio_sample_format_from_string(const char *str);

/** Enum: alsa_sample_format */
typedef enum {
  ALSA_SAMPLE_FORMAT_INVALID = -1,
  ALSA_SAMPLE_FORMAT_S16_LE,
  ALSA_SAMPLE_FORMAT_S24_3_LE,
  ALSA_SAMPLE_FORMAT_S24_4_LE,
  ALSA_SAMPLE_FORMAT_S32_LE,
  ALSA_SAMPLE_FORMAT_F32_LE,
  ALSA_SAMPLE_FORMAT_F64_LE,
  ALSA_SAMPLE_FORMAT_DSD_U8,
  ALSA_SAMPLE_FORMAT_DSD_U16_LE,
  ALSA_SAMPLE_FORMAT_DSD_U16_BE,
  ALSA_SAMPLE_FORMAT_DSD_U32_LE,
  ALSA_SAMPLE_FORMAT_DSD_U32_BE
} alsa_sample_format_t;

const char *alsa_sample_format_to_string(alsa_sample_format_t val);
alsa_sample_format_t alsa_sample_format_from_string(const char *str);

/** Enum: wasapi_sample_format */
typedef enum {
  WASAPI_SAMPLE_FORMAT_INVALID = -1,
  WASAPI_SAMPLE_FORMAT_S16,
  WASAPI_SAMPLE_FORMAT_S24,
  WASAPI_SAMPLE_FORMAT_S32,
  WASAPI_SAMPLE_FORMAT_F32
} wasapi_sample_format_t;

const char *wasapi_sample_format_to_string(wasapi_sample_format_t val);
wasapi_sample_format_t wasapi_sample_format_from_string(const char *str);

/** Enum: asio_sample_format */
typedef enum {
  ASIO_SAMPLE_FORMAT_INVALID = -1,
  ASIO_SAMPLE_FORMAT_S16_LE,
  ASIO_SAMPLE_FORMAT_S24_3_LE,
  ASIO_SAMPLE_FORMAT_S24_4_LE,
  ASIO_SAMPLE_FORMAT_S32_LE,
  ASIO_SAMPLE_FORMAT_F32_LE,
  ASIO_SAMPLE_FORMAT_F64_LE,
  ASIO_SAMPLE_FORMAT_DSD_INT8
} asio_sample_format_t;

const char *asio_sample_format_to_string(asio_sample_format_t val);
asio_sample_format_t asio_sample_format_from_string(const char *str);

/** Enum: binary_sample_format */
typedef enum {
  BINARY_SAMPLE_FORMAT_INVALID = -1,
  BINARY_SAMPLE_FORMAT_S16_LE,
  BINARY_SAMPLE_FORMAT_S16_BE,
  BINARY_SAMPLE_FORMAT_S24_3_LE,
  BINARY_SAMPLE_FORMAT_S24_3_BE,
  BINARY_SAMPLE_FORMAT_S24_4_RJ_LE,
  BINARY_SAMPLE_FORMAT_S24_4_RJ_BE,
  BINARY_SAMPLE_FORMAT_S24_4_LJ_LE,
  BINARY_SAMPLE_FORMAT_S24_4_LJ_BE,
  BINARY_SAMPLE_FORMAT_S32_LE,
  BINARY_SAMPLE_FORMAT_S32_BE,
  BINARY_SAMPLE_FORMAT_F32_LE,
  BINARY_SAMPLE_FORMAT_F32_BE,
  BINARY_SAMPLE_FORMAT_F64_LE,
  BINARY_SAMPLE_FORMAT_F64_BE,
  BINARY_SAMPLE_FORMAT_DSD_U8,
  BINARY_SAMPLE_FORMAT_DSD_U16_LE,
  BINARY_SAMPLE_FORMAT_DSD_U16_BE,
  BINARY_SAMPLE_FORMAT_DSD_U32_LE,
  BINARY_SAMPLE_FORMAT_DSD_U32_BE,
  BINARY_SAMPLE_FORMAT_DSD_U32_REVERSED
} binary_sample_format_t;

const char *binary_sample_format_to_string(binary_sample_format_t val);
binary_sample_format_t binary_sample_format_from_string(const char *str);

typedef struct resampler_config_t resampler_config_t;
typedef struct mixer_source_t mixer_source_t;
typedef struct mixer_mapping_t mixer_mapping_t;
typedef struct mixer_config_t mixer_config_t;
typedef struct compressor_config_t compressor_config_t;
typedef struct noise_gate_config_t noise_gate_config_t;
typedef struct race_config_t race_config_t;
typedef struct lookahead_limiter_processor_config_t lookahead_limiter_processor_config_t;
typedef struct processor_config_t processor_config_t;
typedef struct gain_config_t gain_config_t;
typedef struct volume_config_t volume_config_t;
typedef struct loudness_config_t loudness_config_t;
typedef struct biquad_config_t biquad_config_t;
typedef struct conv_config_t conv_config_t;
typedef struct delay_config_t delay_config_t;
typedef struct peq_band_t peq_band_t;
typedef struct biquad_combo_config_t biquad_combo_config_t;
typedef struct diff_eq_config_t diff_eq_config_t;
typedef struct dither_config_t dither_config_t;
typedef struct clipper_config_t clipper_config_t;
typedef struct lookahead_limiter_filter_config_t lookahead_limiter_filter_config_t;
typedef struct filter_config_t filter_config_t;
typedef struct pipeline_step_config_t pipeline_step_config_t;
typedef struct generator_signal_t generator_signal_t;
typedef struct coreaudio_capture_config_t coreaudio_capture_config_t;
typedef struct coreaudio_playback_config_t coreaudio_playback_config_t;
typedef struct alsa_capture_config_t alsa_capture_config_t;
typedef struct alsa_playback_config_t alsa_playback_config_t;
typedef struct pipewire_capture_config_t pipewire_capture_config_t;
typedef struct pipewire_playback_config_t pipewire_playback_config_t;
typedef struct stdin_capture_config_t stdin_capture_config_t;
typedef struct stdout_playback_config_t stdout_playback_config_t;
typedef struct wasapi_capture_config_t wasapi_capture_config_t;
typedef struct wasapi_playback_config_t wasapi_playback_config_t;
typedef struct asio_capture_config_t asio_capture_config_t;
typedef struct asio_playback_config_t asio_playback_config_t;
typedef struct wav_file_capture_config_t wav_file_capture_config_t;
typedef struct raw_file_capture_config_t raw_file_capture_config_t;
typedef struct raw_file_playback_config_t raw_file_playback_config_t;
typedef struct generator_capture_config_t generator_capture_config_t;
typedef struct capture_device_config_t capture_device_config_t;
typedef struct playback_device_config_t playback_device_config_t;
typedef struct devices_config_t devices_config_t;
typedef struct named_filter_config_t named_filter_config_t;
typedef struct named_mixer_config_t named_mixer_config_t;
typedef struct named_processor_config_t named_processor_config_t;
typedef struct dsp_config_t dsp_config_t;

/** Struct: resampler_config */
struct resampler_config_t {
  resampler_type_t type;
  bool has_profile;
  char profile[32];
  bool has_interpolation;
  char interpolation[32];
  bool has_sinc_len;
  int sinc_len;
  bool has_oversampling_factor;
  int oversampling_factor;
  bool has_window;
  char window[32];
  bool has_f_cutoff;
  double f_cutoff;
};

/** Struct: mixer_source */
struct mixer_source_t {
  size_t channel;
  bool has_gain;
  double gain;
  bool inverted;
  bool mute;
  gain_scale_t scale;
};

/** Struct: mixer_mapping */
struct mixer_mapping_t {
  size_t dest;
  mixer_source_t *sources;
  size_t sources_count;
  bool mute;
};

/** Struct: mixer_config */
struct mixer_config_t {
  char description[256];
  size_t channels_in;
  size_t channels_out;
  mixer_mapping_t *mapping;
  size_t mapping_count;
  bool has_labels;
  char * *labels;
  size_t labels_count;
};

/** Struct: compressor_config */
struct compressor_config_t {
  size_t channels;
  size_t *monitor_channels;
  size_t monitor_channels_count;
  size_t *process_channels;
  size_t process_channels_count;
  double attack;
  time_unit_t attack_unit;
  double release;
  time_unit_t release_unit;
  double threshold;
  double factor;
  bool has_makeup_gain;
  double makeup_gain;
  bool soft_clip;
  bool has_clip_limit;
  double clip_limit;
};

/** Struct: noise_gate_config */
struct noise_gate_config_t {
  size_t channels;
  size_t *monitor_channels;
  size_t monitor_channels_count;
  size_t *process_channels;
  size_t process_channels_count;
  double attack;
  time_unit_t attack_unit;
  double release;
  time_unit_t release_unit;
  double threshold;
  double attenuation;
};

/** Struct: race_config */
struct race_config_t {
  size_t channels;
  size_t channel_a;
  size_t channel_b;
  double delay;
  bool has_subsample_delay;
  bool subsample_delay;
  bool has_delay_unit;
  delay_unit_t delay_unit;
  double attenuation;
};

/** Struct: lookahead_limiter_processor_config */
struct lookahead_limiter_processor_config_t {
  size_t channels;
  size_t *monitor_channels;
  size_t monitor_channels_count;
  size_t *process_channels;
  size_t process_channels_count;
  double limit;
  double attack;
  time_unit_t attack_unit;
  double release;
  time_unit_t release_unit;
  bool delay_processed_only;
};

/** Tagged Union: processor_config */
struct processor_config_t {
  processor_type_t type;
  union {
    compressor_config_t compressor;
    noise_gate_config_t noise_gate;
    race_config_t race;
    lookahead_limiter_processor_config_t lookahead_limiter;
  } parameters;
};

/** Struct: gain_config */
struct gain_config_t {
  bool has_gain;
  double gain;
  gain_scale_t scale;
  bool inverted;
  bool mute;
};

/** Struct: volume_config */
struct volume_config_t {
  fader_t fader;
  bool has_ramp_time_ms;
  double ramp_time_ms;
  bool has_limit;
  double limit;
};

/** Struct: loudness_config */
struct loudness_config_t {
  bool has_reference_level;
  double reference_level;
  bool has_high_boost;
  double high_boost;
  bool has_low_boost;
  double low_boost;
  bool attenuate_mid;
  bool has_high_freq;
  double high_freq;
  bool has_low_freq;
  double low_freq;
  bool has_high_q;
  double high_q;
  bool has_low_q;
  double low_q;
  fader_t fader;
};

/** Struct: biquad_config */
struct biquad_config_t {
  biquad_type_t type;
  bool has_freq;
  double freq;
  bool has_gain;
  double gain;
  bool has_q;
  double q;
  bool has_bandwidth;
  double bandwidth;
  bool has_slope;
  double slope;
  bool has_a1;
  double a1;
  bool has_a2;
  double a2;
  bool has_b0;
  double b0;
  bool has_b1;
  double b1;
  bool has_b2;
  double b2;
  bool has_freq_notch;
  double freq_notch;
  bool has_freq_pole;
  double freq_pole;
  bool has_q_p;
  double q_p;
  bool normalize_at_dc;
  bool has_freq_act;
  double freq_act;
  bool has_q_act;
  double q_act;
  bool has_freq_target;
  double freq_target;
  bool has_q_target;
  double q_target;
  steepness_type_t steepness_type;
};

/** Struct: conv_config */
struct conv_config_t {
  conv_type_t type;
  bool has_filename;
  char filename[512];
  bool has_format;
  char format[32];
  bool has_channel;
  int channel;
  bool has_length;
  int length;
  bool has_skip_bytes_lines;
  size_t skip_bytes_lines;
  bool has_read_bytes_lines;
  size_t read_bytes_lines;
  bool has_values;
  double *values;
  size_t values_count;
};

/** Struct: delay_config */
struct delay_config_t {
  double delay;
  delay_unit_t delay_unit;
  bool subsample;
};

/** Struct: peq_band */
struct peq_band_t {
  double freq;
  double q;
  double gain;
};

/** Struct: biquad_combo_config */
struct biquad_combo_config_t {
  biquad_combo_type_t type;
  bool has_freq;
  double freq;
  bool has_order;
  int order;
  bool has_gain;
  double gain;
  bool has_high_gain;
  double high_gain;
  peq_band_t *bands;
  size_t bands_count;
  bool has_freq_min;
  double freq_min;
  bool has_freq_max;
  double freq_max;
  double *gains;
  size_t gains_count;
};

/** Struct: diff_eq_config */
struct diff_eq_config_t {
  double *a;
  size_t a_count;
  double *b;
  size_t b_count;
};

/** Struct: dither_config */
struct dither_config_t {
  dither_type_t type;
  int bits;
  bool has_amplitude;
  double amplitude;
};

/** Struct: clipper_config */
struct clipper_config_t {
  double clip_limit;
  bool soft_clip;
};

/** Struct: lookahead_limiter_filter_config */
struct lookahead_limiter_filter_config_t {
  double limit;
  double attack;
  time_unit_t attack_unit;
  double release;
  time_unit_t release_unit;
};

/** Tagged Union: filter_config */
struct filter_config_t {
  filter_type_t type;
  union {
    gain_config_t gain;
    volume_config_t volume;
    loudness_config_t loudness;
    biquad_config_t biquad;
    conv_config_t conv;
    delay_config_t delay;
    biquad_combo_config_t biquad_combo;
    diff_eq_config_t diff_eq;
    dither_config_t dither;
    clipper_config_t clipper;
    lookahead_limiter_filter_config_t lookahead_limiter;
  } parameters;
};

/** Struct: pipeline_step_config */
struct pipeline_step_config_t {
  pipeline_step_type_t type;
  char description[256];
  bool has_channel;
  size_t channel;
  bool has_channels;
  size_t *channels;
  size_t channels_count;
  bool has_name;
  char name[128];
  bool has_names;
  char * *names;
  size_t names_count;
  bool bypassed;
};

/** Struct: generator_signal */
struct generator_signal_t {
  signal_type_t type;
  bool has_freq;
  double freq;
  double level;
};

/** Struct: coreaudio_capture_config */
struct coreaudio_capture_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_format;
  coreaudio_sample_format_t format;
  bool has_loopback;
  bool loopback;
};

/** Struct: coreaudio_playback_config */
struct coreaudio_playback_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_format;
  coreaudio_sample_format_t format;
  bool has_exclusive;
  bool exclusive;
  bool has_target_level;
  int target_level;
};

/** Struct: alsa_capture_config */
struct alsa_capture_config_t {
  size_t channels;
  char device[256];
  bool has_format;
  alsa_sample_format_t format;
  bool has_stop_on_inactive;
  bool stop_on_inactive;
  bool has_link_volume_control;
  char link_volume_control[256];
  bool has_link_mute_control;
  char link_mute_control[256];
  bool has_threaded;
  bool threaded;
};

/** Struct: alsa_playback_config */
struct alsa_playback_config_t {
  size_t channels;
  char device[256];
  bool has_format;
  alsa_sample_format_t format;
  bool has_target_level;
  int target_level;
  bool has_threaded;
  bool threaded;
};

/** Struct: pipewire_capture_config */
struct pipewire_capture_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_node_name;
  char node_name[256];
  bool has_node_description;
  char node_description[256];
  bool has_node_group_name;
  char node_group_name[256];
  bool has_autoconnect_to;
  char autoconnect_to[256];
  bool has_loopback;
  bool loopback;
};

/** Struct: pipewire_playback_config */
struct pipewire_playback_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_node_name;
  char node_name[256];
  bool has_node_description;
  char node_description[256];
  bool has_node_group_name;
  char node_group_name[256];
  bool has_autoconnect_to;
  char autoconnect_to[256];
  bool has_target_level;
  int target_level;
};

/** Struct: stdin_capture_config */
struct stdin_capture_config_t {
  size_t channels;
  binary_sample_format_t format;
  bool has_extra_samples;
  int extra_samples;
  bool has_skip_bytes;
  size_t skip_bytes;
  bool has_read_bytes;
  size_t read_bytes;
};

/** Struct: stdout_playback_config */
struct stdout_playback_config_t {
  size_t channels;
  binary_sample_format_t format;
  bool has_wav_header;
  bool wav_header;
};

/** Struct: wasapi_capture_config */
struct wasapi_capture_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_format;
  wasapi_sample_format_t format;
  bool has_exclusive;
  bool exclusive;
  bool has_loopback;
  bool loopback;
  bool has_polling;
  bool polling;
};

/** Struct: wasapi_playback_config */
struct wasapi_playback_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_format;
  wasapi_sample_format_t format;
  bool has_exclusive;
  bool exclusive;
  bool has_polling;
  bool polling;
  bool has_target_level;
  int target_level;
};

/** Struct: asio_capture_config */
struct asio_capture_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_format;
  asio_sample_format_t format;
};

/** Struct: asio_playback_config */
struct asio_playback_config_t {
  size_t channels;
  bool has_device;
  char device[256];
  bool has_format;
  asio_sample_format_t format;
};

/** Struct: wav_file_capture_config */
struct wav_file_capture_config_t {
  size_t channels;
  bool has_filename;
  char filename[512];
  bool has_extra_samples;
  int extra_samples;
  bool has_realtime;
  bool realtime;
};

/** Struct: raw_file_capture_config */
struct raw_file_capture_config_t {
  bool has_filename;
  char filename[512];
  bool has_format;
  binary_sample_format_t format;
  size_t channels;
  bool has_skip_bytes;
  size_t skip_bytes;
  bool has_read_bytes;
  size_t read_bytes;
  bool has_extra_samples;
  int extra_samples;
  bool has_realtime;
  bool realtime;
};

/** Struct: raw_file_playback_config */
struct raw_file_playback_config_t {
  bool has_filename;
  char filename[512];
  bool has_format;
  binary_sample_format_t format;
  size_t channels;
  bool has_wav_header;
  bool wav_header;
  bool has_use_rf64;
  bool use_rf64;
  bool has_realtime;
  bool realtime;
};

/** Struct: generator_capture_config */
struct generator_capture_config_t {
  size_t channels;
  generator_signal_t signal;
};

/** Tagged Union: capture_device_config */
struct capture_device_config_t {
  audio_backend_type_t type;
  bool has_labels;
  char * *labels;
  size_t labels_count;
  bool has_is_wav;
  bool is_wav;
  bool has_bypass_dop;
  bool bypass_dop;
  bool has_dop_cutoff_hz;
  double dop_cutoff_hz;
  union {
    coreaudio_capture_config_t coreaudio;
    alsa_capture_config_t alsa;
    pipewire_capture_config_t pipewire;
    raw_file_capture_config_t raw_file;
    stdin_capture_config_t stdin_in;
    generator_capture_config_t generator;
    wasapi_capture_config_t wasapi;
    asio_capture_config_t asio;
    wav_file_capture_config_t wav_file;
  } cfg;
};

/** Tagged Union: playback_device_config */
struct playback_device_config_t {
  audio_backend_type_t type;
  bool has_labels;
  char * *labels;
  size_t labels_count;
  bool has_is_wav;
  bool is_wav;
  bool has_output_dop;
  bool output_dop;
  bool has_dsd_encoder_filter;
  sdm_filter_t dsd_encoder_filter;
  union {
    coreaudio_playback_config_t coreaudio;
    alsa_playback_config_t alsa;
    pipewire_playback_config_t pipewire;
    raw_file_playback_config_t raw_file;
    stdout_playback_config_t stdout_out;
    wasapi_playback_config_t wasapi;
    asio_playback_config_t asio;
  } cfg;
};

/** Struct: devices_config */
struct devices_config_t {
  size_t samplerate;
  size_t chunksize;
  bool has_enable_rate_adjust;
  bool enable_rate_adjust;
  bool has_target_level;
  int target_level;
  bool has_adjust_interval_s;
  double adjust_interval_s;
  bool has_resampler;
  resampler_config_t resampler;
  capture_device_config_t capture;
  playback_device_config_t playback;
  bool has_capture_samplerate;
  size_t capture_samplerate;
  bool has_silence_threshold;
  double silence_threshold;
  bool has_silence_timeout_s;
  double silence_timeout_s;
  bool has_volume_ramp_time_ms;
  double volume_ramp_time_ms;
  bool has_volume_limit;
  double volume_limit;
  bool has_queuelimit;
  int queuelimit;
  bool has_stop_on_rate_change;
  bool stop_on_rate_change;
  bool has_rate_measure_interval_s;
  double rate_measure_interval_s;
  bool has_multithreaded;
  bool multithreaded;
  bool has_worker_threads;
  int worker_threads;
};

/** Struct: dsp_config */
struct dsp_config_t {
  char title[128];
  char description[256];
  devices_config_t devices;
  named_filter_config_t *filters;
  size_t filters_count;
  named_mixer_config_t *mixers;
  size_t mixers_count;
  named_processor_config_t *processors;
  size_t processors_count;
  pipeline_step_config_t *pipeline;
  size_t pipeline_count;
};

/** Named Map Item: named_filter_config_t */
struct named_filter_config_t {
  char name[128];
  char description[256];
  filter_config_t filter;
};

/** Named Map Item: named_mixer_config_t */
struct named_mixer_config_t {
  char name[128];
  mixer_config_t mixer;
};

/** Named Map Item: named_processor_config_t */
struct named_processor_config_t {
  char name[128];
  char description[256];
  processor_config_t processor;
};

void resampler_config_init(resampler_config_t *out);
bool resampler_config_equal(const resampler_config_t *a, const resampler_config_t *b);
int parse_resampler_config(const cJSON *obj, const char *ctx, resampler_config_t *out, config_error_t *err);
cJSON *serialize_resampler_config(const resampler_config_t *in);
void free_resampler_config_contents(resampler_config_t *in);

void mixer_source_init(mixer_source_t *out);
bool mixer_source_equal(const mixer_source_t *a, const mixer_source_t *b);
int parse_mixer_source(const cJSON *obj, const char *ctx, mixer_source_t *out, config_error_t *err);
cJSON *serialize_mixer_source(const mixer_source_t *in);
void free_mixer_source_contents(mixer_source_t *in);
double mixer_source_get_gain(const mixer_source_t *in);

void mixer_mapping_init(mixer_mapping_t *out);
bool mixer_mapping_equal(const mixer_mapping_t *a, const mixer_mapping_t *b);
int parse_mixer_mapping(const cJSON *obj, const char *ctx, mixer_mapping_t *out, config_error_t *err);
cJSON *serialize_mixer_mapping(const mixer_mapping_t *in);
void free_mixer_mapping_contents(mixer_mapping_t *in);

void mixer_config_init(mixer_config_t *out);
bool mixer_config_equal(const mixer_config_t *a, const mixer_config_t *b);
int parse_mixer_config(const cJSON *obj, const char *ctx, mixer_config_t *out, config_error_t *err);
cJSON *serialize_mixer_config(const mixer_config_t *in);
void free_mixer_config_contents(mixer_config_t *in);

void compressor_config_init(compressor_config_t *out);
bool compressor_config_equal(const compressor_config_t *a, const compressor_config_t *b);
int parse_compressor_config(const cJSON *obj, const char *ctx, compressor_config_t *out, config_error_t *err);
cJSON *serialize_compressor_config(const compressor_config_t *in);
void free_compressor_config_contents(compressor_config_t *in);
double compressor_config_get_makeup_gain(const compressor_config_t *in);
double compressor_config_get_clip_limit(const compressor_config_t *in);

void noise_gate_config_init(noise_gate_config_t *out);
bool noise_gate_config_equal(const noise_gate_config_t *a, const noise_gate_config_t *b);
int parse_noise_gate_config(const cJSON *obj, const char *ctx, noise_gate_config_t *out, config_error_t *err);
cJSON *serialize_noise_gate_config(const noise_gate_config_t *in);
void free_noise_gate_config_contents(noise_gate_config_t *in);

void race_config_init(race_config_t *out);
bool race_config_equal(const race_config_t *a, const race_config_t *b);
int parse_race_config(const cJSON *obj, const char *ctx, race_config_t *out, config_error_t *err);
cJSON *serialize_race_config(const race_config_t *in);
void free_race_config_contents(race_config_t *in);

void lookahead_limiter_processor_config_init(lookahead_limiter_processor_config_t *out);
bool lookahead_limiter_processor_config_equal(const lookahead_limiter_processor_config_t *a, const lookahead_limiter_processor_config_t *b);
int parse_lookahead_limiter_processor_config(const cJSON *obj, const char *ctx, lookahead_limiter_processor_config_t *out, config_error_t *err);
cJSON *serialize_lookahead_limiter_processor_config(const lookahead_limiter_processor_config_t *in);
void free_lookahead_limiter_processor_config_contents(lookahead_limiter_processor_config_t *in);

void processor_config_init(processor_config_t *out);
bool processor_config_equal(const processor_config_t *a, const processor_config_t *b);
int parse_processor_config(const cJSON *obj, const char *ctx, processor_config_t *out, config_error_t *err);
cJSON *serialize_processor_config(const processor_config_t *in);
void free_processor_config_contents(processor_config_t *in);

void gain_config_init(gain_config_t *out);
bool gain_config_equal(const gain_config_t *a, const gain_config_t *b);
int parse_gain_config(const cJSON *obj, const char *ctx, gain_config_t *out, config_error_t *err);
cJSON *serialize_gain_config(const gain_config_t *in);
void free_gain_config_contents(gain_config_t *in);
double gain_config_get_gain(const gain_config_t *in);

void volume_config_init(volume_config_t *out);
bool volume_config_equal(const volume_config_t *a, const volume_config_t *b);
int parse_volume_config(const cJSON *obj, const char *ctx, volume_config_t *out, config_error_t *err);
cJSON *serialize_volume_config(const volume_config_t *in);
void free_volume_config_contents(volume_config_t *in);
double volume_config_get_ramp_time_ms(const volume_config_t *in);
double volume_config_get_limit(const volume_config_t *in);

void loudness_config_init(loudness_config_t *out);
bool loudness_config_equal(const loudness_config_t *a, const loudness_config_t *b);
int parse_loudness_config(const cJSON *obj, const char *ctx, loudness_config_t *out, config_error_t *err);
cJSON *serialize_loudness_config(const loudness_config_t *in);
void free_loudness_config_contents(loudness_config_t *in);

void biquad_config_init(biquad_config_t *out);
bool biquad_config_equal(const biquad_config_t *a, const biquad_config_t *b);
int parse_biquad_config(const cJSON *obj, const char *ctx, biquad_config_t *out, config_error_t *err);
cJSON *serialize_biquad_config(const biquad_config_t *in);
void free_biquad_config_contents(biquad_config_t *in);

void conv_config_init(conv_config_t *out);
bool conv_config_equal(const conv_config_t *a, const conv_config_t *b);
int parse_conv_config(const cJSON *obj, const char *ctx, conv_config_t *out, config_error_t *err);
cJSON *serialize_conv_config(const conv_config_t *in);
void free_conv_config_contents(conv_config_t *in);

void delay_config_init(delay_config_t *out);
bool delay_config_equal(const delay_config_t *a, const delay_config_t *b);
int parse_delay_config(const cJSON *obj, const char *ctx, delay_config_t *out, config_error_t *err);
cJSON *serialize_delay_config(const delay_config_t *in);
void free_delay_config_contents(delay_config_t *in);

void peq_band_init(peq_band_t *out);
bool peq_band_equal(const peq_band_t *a, const peq_band_t *b);
int parse_peq_band(const cJSON *obj, const char *ctx, peq_band_t *out, config_error_t *err);
cJSON *serialize_peq_band(const peq_band_t *in);
void free_peq_band_contents(peq_band_t *in);

void biquad_combo_config_init(biquad_combo_config_t *out);
bool biquad_combo_config_equal(const biquad_combo_config_t *a, const biquad_combo_config_t *b);
int parse_biquad_combo_config(const cJSON *obj, const char *ctx, biquad_combo_config_t *out, config_error_t *err);
cJSON *serialize_biquad_combo_config(const biquad_combo_config_t *in);
void free_biquad_combo_config_contents(biquad_combo_config_t *in);

void diff_eq_config_init(diff_eq_config_t *out);
bool diff_eq_config_equal(const diff_eq_config_t *a, const diff_eq_config_t *b);
int parse_diff_eq_config(const cJSON *obj, const char *ctx, diff_eq_config_t *out, config_error_t *err);
cJSON *serialize_diff_eq_config(const diff_eq_config_t *in);
void free_diff_eq_config_contents(diff_eq_config_t *in);

void dither_config_init(dither_config_t *out);
bool dither_config_equal(const dither_config_t *a, const dither_config_t *b);
int parse_dither_config(const cJSON *obj, const char *ctx, dither_config_t *out, config_error_t *err);
cJSON *serialize_dither_config(const dither_config_t *in);
void free_dither_config_contents(dither_config_t *in);
double dither_config_get_amplitude(const dither_config_t *in);

void clipper_config_init(clipper_config_t *out);
bool clipper_config_equal(const clipper_config_t *a, const clipper_config_t *b);
int parse_clipper_config(const cJSON *obj, const char *ctx, clipper_config_t *out, config_error_t *err);
cJSON *serialize_clipper_config(const clipper_config_t *in);
void free_clipper_config_contents(clipper_config_t *in);

void lookahead_limiter_filter_config_init(lookahead_limiter_filter_config_t *out);
bool lookahead_limiter_filter_config_equal(const lookahead_limiter_filter_config_t *a, const lookahead_limiter_filter_config_t *b);
int parse_lookahead_limiter_filter_config(const cJSON *obj, const char *ctx, lookahead_limiter_filter_config_t *out, config_error_t *err);
cJSON *serialize_lookahead_limiter_filter_config(const lookahead_limiter_filter_config_t *in);
void free_lookahead_limiter_filter_config_contents(lookahead_limiter_filter_config_t *in);

void filter_config_init(filter_config_t *out);
bool filter_config_equal(const filter_config_t *a, const filter_config_t *b);
int parse_filter_config(const cJSON *obj, const char *ctx, filter_config_t *out, config_error_t *err);
cJSON *serialize_filter_config(const filter_config_t *in);
void free_filter_config_contents(filter_config_t *in);

void pipeline_step_config_init(pipeline_step_config_t *out);
bool pipeline_step_config_equal(const pipeline_step_config_t *a, const pipeline_step_config_t *b);
int parse_pipeline_step_config(const cJSON *obj, const char *ctx, pipeline_step_config_t *out, config_error_t *err);
cJSON *serialize_pipeline_step_config(const pipeline_step_config_t *in);
void free_pipeline_step_config_contents(pipeline_step_config_t *in);

void generator_signal_init(generator_signal_t *out);
bool generator_signal_equal(const generator_signal_t *a, const generator_signal_t *b);
int parse_generator_signal(const cJSON *obj, const char *ctx, generator_signal_t *out, config_error_t *err);
cJSON *serialize_generator_signal(const generator_signal_t *in);
void free_generator_signal_contents(generator_signal_t *in);
double generator_signal_get_freq(const generator_signal_t *in);

void coreaudio_capture_config_init(coreaudio_capture_config_t *out);
bool coreaudio_capture_config_equal(const coreaudio_capture_config_t *a, const coreaudio_capture_config_t *b);
int parse_coreaudio_capture_config(const cJSON *obj, const char *ctx, coreaudio_capture_config_t *out, config_error_t *err);
cJSON *serialize_coreaudio_capture_config(const coreaudio_capture_config_t *in);
void free_coreaudio_capture_config_contents(coreaudio_capture_config_t *in);

void coreaudio_playback_config_init(coreaudio_playback_config_t *out);
bool coreaudio_playback_config_equal(const coreaudio_playback_config_t *a, const coreaudio_playback_config_t *b);
int parse_coreaudio_playback_config(const cJSON *obj, const char *ctx, coreaudio_playback_config_t *out, config_error_t *err);
cJSON *serialize_coreaudio_playback_config(const coreaudio_playback_config_t *in);
void free_coreaudio_playback_config_contents(coreaudio_playback_config_t *in);

void alsa_capture_config_init(alsa_capture_config_t *out);
bool alsa_capture_config_equal(const alsa_capture_config_t *a, const alsa_capture_config_t *b);
int parse_alsa_capture_config(const cJSON *obj, const char *ctx, alsa_capture_config_t *out, config_error_t *err);
cJSON *serialize_alsa_capture_config(const alsa_capture_config_t *in);
void free_alsa_capture_config_contents(alsa_capture_config_t *in);

void alsa_playback_config_init(alsa_playback_config_t *out);
bool alsa_playback_config_equal(const alsa_playback_config_t *a, const alsa_playback_config_t *b);
int parse_alsa_playback_config(const cJSON *obj, const char *ctx, alsa_playback_config_t *out, config_error_t *err);
cJSON *serialize_alsa_playback_config(const alsa_playback_config_t *in);
void free_alsa_playback_config_contents(alsa_playback_config_t *in);

void pipewire_capture_config_init(pipewire_capture_config_t *out);
bool pipewire_capture_config_equal(const pipewire_capture_config_t *a, const pipewire_capture_config_t *b);
int parse_pipewire_capture_config(const cJSON *obj, const char *ctx, pipewire_capture_config_t *out, config_error_t *err);
cJSON *serialize_pipewire_capture_config(const pipewire_capture_config_t *in);
void free_pipewire_capture_config_contents(pipewire_capture_config_t *in);

void pipewire_playback_config_init(pipewire_playback_config_t *out);
bool pipewire_playback_config_equal(const pipewire_playback_config_t *a, const pipewire_playback_config_t *b);
int parse_pipewire_playback_config(const cJSON *obj, const char *ctx, pipewire_playback_config_t *out, config_error_t *err);
cJSON *serialize_pipewire_playback_config(const pipewire_playback_config_t *in);
void free_pipewire_playback_config_contents(pipewire_playback_config_t *in);

void stdin_capture_config_init(stdin_capture_config_t *out);
bool stdin_capture_config_equal(const stdin_capture_config_t *a, const stdin_capture_config_t *b);
int parse_stdin_capture_config(const cJSON *obj, const char *ctx, stdin_capture_config_t *out, config_error_t *err);
cJSON *serialize_stdin_capture_config(const stdin_capture_config_t *in);
void free_stdin_capture_config_contents(stdin_capture_config_t *in);

void stdout_playback_config_init(stdout_playback_config_t *out);
bool stdout_playback_config_equal(const stdout_playback_config_t *a, const stdout_playback_config_t *b);
int parse_stdout_playback_config(const cJSON *obj, const char *ctx, stdout_playback_config_t *out, config_error_t *err);
cJSON *serialize_stdout_playback_config(const stdout_playback_config_t *in);
void free_stdout_playback_config_contents(stdout_playback_config_t *in);

void wasapi_capture_config_init(wasapi_capture_config_t *out);
bool wasapi_capture_config_equal(const wasapi_capture_config_t *a, const wasapi_capture_config_t *b);
int parse_wasapi_capture_config(const cJSON *obj, const char *ctx, wasapi_capture_config_t *out, config_error_t *err);
cJSON *serialize_wasapi_capture_config(const wasapi_capture_config_t *in);
void free_wasapi_capture_config_contents(wasapi_capture_config_t *in);

void wasapi_playback_config_init(wasapi_playback_config_t *out);
bool wasapi_playback_config_equal(const wasapi_playback_config_t *a, const wasapi_playback_config_t *b);
int parse_wasapi_playback_config(const cJSON *obj, const char *ctx, wasapi_playback_config_t *out, config_error_t *err);
cJSON *serialize_wasapi_playback_config(const wasapi_playback_config_t *in);
void free_wasapi_playback_config_contents(wasapi_playback_config_t *in);

void asio_capture_config_init(asio_capture_config_t *out);
bool asio_capture_config_equal(const asio_capture_config_t *a, const asio_capture_config_t *b);
int parse_asio_capture_config(const cJSON *obj, const char *ctx, asio_capture_config_t *out, config_error_t *err);
cJSON *serialize_asio_capture_config(const asio_capture_config_t *in);
void free_asio_capture_config_contents(asio_capture_config_t *in);

void asio_playback_config_init(asio_playback_config_t *out);
bool asio_playback_config_equal(const asio_playback_config_t *a, const asio_playback_config_t *b);
int parse_asio_playback_config(const cJSON *obj, const char *ctx, asio_playback_config_t *out, config_error_t *err);
cJSON *serialize_asio_playback_config(const asio_playback_config_t *in);
void free_asio_playback_config_contents(asio_playback_config_t *in);

void wav_file_capture_config_init(wav_file_capture_config_t *out);
bool wav_file_capture_config_equal(const wav_file_capture_config_t *a, const wav_file_capture_config_t *b);
int parse_wav_file_capture_config(const cJSON *obj, const char *ctx, wav_file_capture_config_t *out, config_error_t *err);
cJSON *serialize_wav_file_capture_config(const wav_file_capture_config_t *in);
void free_wav_file_capture_config_contents(wav_file_capture_config_t *in);

void raw_file_capture_config_init(raw_file_capture_config_t *out);
bool raw_file_capture_config_equal(const raw_file_capture_config_t *a, const raw_file_capture_config_t *b);
int parse_raw_file_capture_config(const cJSON *obj, const char *ctx, raw_file_capture_config_t *out, config_error_t *err);
cJSON *serialize_raw_file_capture_config(const raw_file_capture_config_t *in);
void free_raw_file_capture_config_contents(raw_file_capture_config_t *in);

void raw_file_playback_config_init(raw_file_playback_config_t *out);
bool raw_file_playback_config_equal(const raw_file_playback_config_t *a, const raw_file_playback_config_t *b);
int parse_raw_file_playback_config(const cJSON *obj, const char *ctx, raw_file_playback_config_t *out, config_error_t *err);
cJSON *serialize_raw_file_playback_config(const raw_file_playback_config_t *in);
void free_raw_file_playback_config_contents(raw_file_playback_config_t *in);

void generator_capture_config_init(generator_capture_config_t *out);
bool generator_capture_config_equal(const generator_capture_config_t *a, const generator_capture_config_t *b);
int parse_generator_capture_config(const cJSON *obj, const char *ctx, generator_capture_config_t *out, config_error_t *err);
cJSON *serialize_generator_capture_config(const generator_capture_config_t *in);
void free_generator_capture_config_contents(generator_capture_config_t *in);

void capture_device_config_init(capture_device_config_t *out);
bool capture_device_config_equal(const capture_device_config_t *a, const capture_device_config_t *b);
int parse_capture_device_config(const cJSON *obj, const char *ctx, capture_device_config_t *out, config_error_t *err);
cJSON *serialize_capture_device_config(const capture_device_config_t *in);
void free_capture_device_config_contents(capture_device_config_t *in);

void playback_device_config_init(playback_device_config_t *out);
bool playback_device_config_equal(const playback_device_config_t *a, const playback_device_config_t *b);
int parse_playback_device_config(const cJSON *obj, const char *ctx, playback_device_config_t *out, config_error_t *err);
cJSON *serialize_playback_device_config(const playback_device_config_t *in);
void free_playback_device_config_contents(playback_device_config_t *in);

void devices_config_init(devices_config_t *out);
bool devices_config_equal(const devices_config_t *a, const devices_config_t *b);
int parse_devices_config(const cJSON *obj, const char *ctx, devices_config_t *out, config_error_t *err);
cJSON *serialize_devices_config(const devices_config_t *in);
void free_devices_config_contents(devices_config_t *in);

void dsp_config_init(dsp_config_t *out);
bool dsp_config_equal(const dsp_config_t *a, const dsp_config_t *b);
int parse_dsp_config(const cJSON *obj, const char *ctx, dsp_config_t *out, config_error_t *err);
cJSON *serialize_dsp_config(const dsp_config_t *in);
void free_dsp_config_contents(dsp_config_t *in);

#endif /* CONFIG_GEN_H */

/* clang-format on */
