# CDSP CTest Discovery Script
# Automatically called post-build to discover individual test cases from test_runner

if(NOT DEFINED TEST_EXECUTABLE)
    message(FATAL_ERROR "TEST_EXECUTABLE must be specified")
endif()

if(NOT DEFINED CTEST_FILE)
    message(FATAL_ERROR "CTEST_FILE must be specified")
endif()

# Execute test runner to list all test names
execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list
    OUTPUT_VARIABLE TEST_OUTPUT
    RESULT_VARIABLE RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT RESULT EQUAL 0)
    message(WARNING "Failed to query tests from ${TEST_EXECUTABLE}: ${RESULT}")
    return()
endif()

string(REPLACE "\n" ";" TEST_LIST "${TEST_OUTPUT}")
list(REMOVE_DUPLICATES TEST_LIST)

# Generate CTest commands
set(CTEST_CONTENT "# Auto-generated by CdspDiscoverTests.cmake\n")
string(APPEND CTEST_CONTENT "set(CTEST_CUSTOM_TESTS_COUNT 0)\n\n")

foreach(TEST_NAME IN LISTS TEST_LIST)
    string(STRIP "${TEST_NAME}" TEST_NAME)
    if("${TEST_NAME}" STREQUAL "")
        continue()
    endif()

    # Categorize test labels based on prefix/name
    set(TEST_LABEL "unit")
    if("${TEST_NAME}" MATCHES "^(Pipeline|DSPEngine)")
        set(TEST_LABEL "unit;pipeline")
    elseif("${TEST_NAME}" MATCHES "^(Biquad|Convolution|Filters?|Loudness|Gain|Volume|Delay|DiffEq|Dither|Clipper|Limiter)")
        set(TEST_LABEL "unit;filter")
    elseif("${TEST_NAME}" MATCHES "^(Resampler|Sync|Async|Slip)")
        set(TEST_LABEL "unit;resampler")
    elseif("${TEST_NAME}" MATCHES "^(DoP|DSD|SDM)")
        set(TEST_LABEL "unit;dsd")
    elseif("${TEST_NAME}" MATCHES "^(Mixer)")
        set(TEST_LABEL "unit;mixer")
    elseif("${TEST_NAME}" MATCHES "^(FFT|MixedRadix|RealFFT)")
        set(TEST_LABEL "unit;fft")
    elseif("${TEST_NAME}" MATCHES "^(Backend|FileBackend|CoreAudio|ALSA|PipeWire|WASAPI|ASIO)")
        set(TEST_LABEL "unit;backend")
    elseif("${TEST_NAME}" MATCHES "^(WebSocket|YamlConverter)")
        set(TEST_LABEL "unit;server")
    elseif("${TEST_NAME}" MATCHES "AllocationFree")
        set(TEST_LABEL "unit;realtime")
    endif()

    set(TEST_PROPERTIES "LABELS \"${TEST_LABEL}\" TIMEOUT 30 ENVIRONMENT \"TSAN_OPTIONS=suppressions=${CMAKE_CURRENT_LIST_DIR}/tsan_suppressions.txt:second_deadlock_stack=1;LSAN_OPTIONS=suppressions=${CMAKE_CURRENT_LIST_DIR}/lsan_suppressions.txt\"")

    if("${TEST_NAME}" MATCHES "(CoreAudio)")
        string(APPEND TEST_PROPERTIES " RESOURCE_LOCK \"coreaudio_hardware\"")
    elseif("${TEST_NAME}" MATCHES "ALSA")
        string(APPEND TEST_PROPERTIES " RESOURCE_LOCK \"alsa_hardware\"")
    elseif("${TEST_NAME}" MATCHES "PipeWire")
        string(APPEND TEST_PROPERTIES " RESOURCE_LOCK \"pipewire_hardware\"")
    elseif("${TEST_NAME}" MATCHES "WASAPI")
        string(APPEND TEST_PROPERTIES " RESOURCE_LOCK \"wasapi_hardware\"")
    elseif("${TEST_NAME}" MATCHES "ASIO")
        string(APPEND TEST_PROPERTIES " RESOURCE_LOCK \"asio_hardware\"")
    endif()

    string(APPEND CTEST_CONTENT "add_test(\"${TEST_NAME}\" \"${TEST_EXECUTABLE}\" \"--run\" \"${TEST_NAME}\")\n")
    string(APPEND CTEST_CONTENT "set_tests_properties(\"${TEST_NAME}\" PROPERTIES ${TEST_PROPERTIES})\n\n")
endforeach()

# Write atomically to CTest file
file(WRITE "${CTEST_FILE}" "${CTEST_CONTENT}")
message(STATUS "CTest: Discovered ${CMAKE_CURRENT_LIST_FILE} -> registered test cases in ${CTEST_FILE}")
