# CMake Toolchain file for cross-compiling Monitor-Qt from macOS to Windows (MinGW-w64 x86_64)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Set compilers (MinGW-w64 cross compiler)
if(NOT CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
endif()
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
endif()
if(NOT CMAKE_RC_COMPILER)
    set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
endif()

# Host Qt for macOS (matches target Qt 6.5.2 version)
get_filename_component(USER_HOME "~" REALPATH)
if(EXISTS "${USER_HOME}/Qt6-Mac/6.5.2/macos")
    set(QT_HOST_PATH "${USER_HOME}/Qt6-Mac/6.5.2/macos" CACHE PATH "Host Qt Path for MOC/UIC/RCC")
endif()

# Search rules for cross-compilation
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
